### ISSUE TITLE
Test runner blows up on first run: [ERROR] TestRunnerChildProcessAdapter

### ISSUE THREAD

**Issue by NodeGuy** [stryker-mutator/stryker#1034]
### Summary

I'm trying to use Stryker for the first time on https://gitlab.com/NodeGuy/channel and it appears to break when it hits a mutant (I'm guessing):

```shell
$ stryker run
[2018-07-18 18:00:11.550] [INFO] ConfigReader - Using stryker.conf.js in the current working directory.
[2018-07-18 18:00:11.952] [INFO] InputFileResolver - Found 1 of 20 file(s) to be mutated.
[2018-07-18 18:00:11.955] [INFO] InitialTestExecutor - Starting initial test run. This may take a while.
[2018-07-18 18:00:14.545] [INFO] InitialTestExecutor - Initial test run succeeded. Ran 49 tests in 2 seconds (net 100 ms, overhead 85 ms).
[2018-07-18 18:00:14.962] [INFO] Stryker - 252 Mutant(s) generated
[2018-07-18 18:00:15.055] [INFO] SandboxPool - Creating 8 test runners (based on CPU count)
Mutation testing  [======                                            ] 12% (ETC 30.1s) 31/252 tested (4 survived)[2018-07-18 18:00:21.788] [ERROR] TestRunnerChildProcessAdapter - /Users/david/Documents/projects/channel/.stryker-tmp/sandbox7828783/lib/index.js:85
      const { cancelled, resolve } = pushes[resolvedIndex];
              ^

TypeError: Cannot destructure property `cancelled` of 'undefined' or 'null'.
    at Immediate.processOrders (/Users/david/Documents/projects/channel/.stryker-tmp/sandbox7828783/lib/index.js:85:44)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)

[2018-07-18 18:00:21.797] [ERROR] TestRunnerChildProcessAdapter - Child process exited with non-zero exit code 1. Last 10 message from the child process were: 
	[2018-07-18 18:00:15.934] [DEBUG] PluginLoader - Loading stryker-* from /Users/david/Documents/projects/channel/node_modules
[2018-07-18 18:00:15.942] [DEBUG] PluginLoader - Loading plugins stryker-javascript-mutator (matched with expression stryker-*)
[2018-07-18 18:00:15.943] [DEBUG] PluginLoader - Loading plugins stryker-mocha-framework (matched with expression stryker-*)
[2018-07-18 18:00:15.943] [DEBUG] PluginLoader - Loading plugins stryker-mocha-runner (matched with expression stryker-*)

	[2018-07-18 18:00:15.943] [DEBUG] PluginLoader - Loading plugins stryker-javascript-mutator

	[2018-07-18 18:00:17.309] [DEBUG] PluginLoader - Loading plugins stryker-mocha-framework

	[2018-07-18 18:00:17.326] [DEBUG] PluginLoader - Loading plugins stryker-mocha-runner

	[2018-07-18 18:00:17.590] [DEBUG] IsolatedTestRunnerAdapterWorker - Changing current working directory for this process to /Users/david/Documents/projects/channel/.stryker-tmp/sandbox7828783

[2018-07-18 18:00:21.799] [ERROR] StrykerCli - an error occurred Test runner child process exited with non-zero exit code 1
```

### Stryker config

```js
module.exports = function(config) {
  config.set({
    testRunner: "mocha",
    mutator: "javascript",
    transpilers: [],
    reporter: ["clear-text", "progress"],
    testFramework: "mocha",
    coverageAnalysis: "perTest",
    mutate: ["lib/**/*.js"]
  });
};

```

### Stryker environment

```
$ npm ls | grep stryker
├─┬ stryker@0.24.2
├─┬ stryker-api@0.17.3
├─┬ stryker-javascript-mutator@0.7.3
├─┬ stryker-mocha-framework@0.10.3
└─┬ stryker-mocha-runner@0.12.3
```

### Your Environment
| software         | version(s)
| ---------------- | -------  
| node             |  v9.11.1
| npm              | 5.6.0
| Operating System | macOS 10.13.4

**Comment by simondel** [comment]
Thanks for opening this issue! I have created a branch to resolve this issue.

By the way, your mutation score is 93.44% 🥇

**Comment by simondel** [comment]
Fixed with:
stryker@0.25.1
stryker-api@0.18.0
stryker-javascript-mutator@0.8.0
stryker-mocha-framework@0.11.0
stryker-mocha-runner@0.13.0

**Comment by NodeGuy** [comment]
Wowee, that was fast!  Thanks!

**Comment by simondel** [comment]
During testing I noticed that Stryker does not shut down after it is done. This may be due to your tests still using some resources on your system.

**Comment by nicojs** [comment]
Might be fixed on the latest branch I've been working on. 976-silent-testrunners
