### ISSUE TITLE
Stryker does not work in jest with jest.mock

### ISSUE THREAD

**Issue by eskimoblood** [stryker-mutator/stryker#1106]
### Summary

Running stryker on jest tests fails when the test is using mocks

```
11:51:30 (21401) ERROR InitialTestExecutor One or more tests resulted in an error:
	  ● Test suite failed to run

    /path/to/test.spec.js: babel-plugin-jest-hoist: The module factory of `jest.mock()` is not allowed to reference any out-of-scope variables.
    Invalid variable access: _react2
    Whitelisted objects: Array, ArrayBuffer, Boolean, DataView, Date, Error, EvalError, Float32Array, Float64Array, Function, Generator, GeneratorFunction, Infinity, Int16Array, Int32Array, Int8Array, InternalError, Intl, JSON, Map, Math, NaN, Number, Object, Promise, Proxy, RangeError, ReferenceError, Reflect, RegExp, Set, String, Symbol, SyntaxError, TypeError, URIError, Uint16Array, Uint32Array, Uint8Array, Uint8ClampedArray, WeakMap, WeakSet, arguments, console, expect, isNaN, jest, parseFloat, parseInt, require, undefined, DTRACE_NET_SERVER_CONNECTION, DTRACE_NET_STREAM_END, DTRACE_HTTP_SERVER_REQUEST, DTRACE_HTTP_SERVER_RESPONSE, DTRACE_HTTP_CLIENT_REQUEST, DTRACE_HTTP_CLIENT_RESPONSE, global, process, Buffer, clearImmediate, clearInterval, clearTimeout, setImmediate, setInterval, setTimeout, @@any-promise/REGISTRATION, __extends, __assign, __rest, __decorate, __param, __metadata, __awaiter, __generator, __exportStar, __values, __read, __spread, __await, __asyncGenerator, __asyncDelegator, __asyncValues, __makeTemplateObject, __importStar, __importDefault, __core-js_shared__.
    Note: This is a precaution to guard against uninitialized mock variables. If it is ensured that the mock is required lazily, variable names prefixed with `mock` are permitted.

      at invariant (../../node_modules/babel-plugin-jest-hoist/build/index.js:14:11)
      at newFn (../../node_modules/babel-traverse/lib/visitors.js:276:21)
      at NodePath._call (../../node_modules/babel-traverse/lib/path/context.js:76:18)
      at NodePath.call (../../node_modules/babel-traverse/lib/path/context.js:48:17)
      at NodePath.visit (../../node_modules/babel-traverse/lib/path/context.js:105:12)
      at TraversalContext.visitQueue (../../node_modules/babel-traverse/lib/context.js:150:16)
      at TraversalContext.visitMultiple (../../node_modules/babel-traverse/lib/context.js:103:17)
```
### Stryker config

```js
module.exports = function(config) {
    config.set({
        testRunner: 'jest',
        mutator: 'javascript',
        transpilers: ['babel'],
        babelrcFile: '.babelrc',
        reporters: ['html', 'clear-text', 'progress', 'dashboard'],
        packageManager: 'yarn',
        coverageAnalysis: 'off',
        mutate: ['src/**/*.js'],
    })
}

```

### Stryker environment

```
 "stryker": "^0.29.0",
 "stryker-api": "^0.21.0",
 "stryker-babel-transpiler": "^0.7.1",
  "stryker-html-reporter": "^0.16.1",
  "stryker-javascript-mutator": "^0.9.1",
  "stryker-jest-runner": "^1.1.1",
```

```
 jest@23.1.0
```

### Your Environment

| software         | version(s)
| ---------------- | -------  
| node             | 
| npm              | 
| Operating System | 

### Add stryker.log

```
12:01:09 (23493) INFO ConfigReader Using stryker.conf.js in the current working directory.
12:01:09 (23493) DEBUG PluginLoader Loading stryker-* from path/to/projectnode_modules
12:01:09 (23493) DEBUG Stryker Using config: {"logLevel":"info","fileLogLevel":"trace","timeoutMS":5000,"timeoutFactor":1.5,"plugins":["stryker-*"],"port":9234,"reporter":[],"reporters":["html","clear-text","progress","dashboard"],"coverageAnalysis":"off","testRunner":"jest","mutator":"javascript","transpilers":["babel"],"maxConcurrentTestRunners":null,"symlinkNodeModules":true,"thresholds":{"high":80,"low":60,"break":null},"babelrcFile":".babelrc","packageManager":"yarn","mutate":["src/**/*.js"],"configFile":"stryker.conf.js","jest":{"project":"default","config":{"testRegex":"(<rootDir>/test/.*|)\\.spec\\.jsx?$","transform":{"^.+\\.js$":"babel-jest","^.+\\.graphql$":"<rootDir>/tools/jest/graphqlTransformer.js","\\.(txt|jpg|svg|png)$":"<rootDir>/tools/jest/fileTransformer.js"},"moduleNameMapper":{"\\.(css|less)$":"identity-obj-proxy"},"modulePathIgnorePatterns":["<rootDir>/build/"],"moduleFileExtensions":["js","json","graphql"],"snapshotSerializers":["enzyme-to-json/serializer"],"collectCoverageFrom":["src/**/*.js"],"coveragePathIgnorePatterns":["src/config/","src/flow/","src/graphql","src/styles","src/types","types.js","styles.js"],"coverageReporters":["cobertura","lcov","text","text-summary","json-summary"],"setupTestFrameworkScriptFile":"<rootDir>/tools/jest/setup-jasmine-env.js","setupFiles":["<rootDir>/tools/jest/setup-react-adapter.js"],"watchPlugins":["jest-watch-typeahead/filename","jest-watch-typeahead/testname"],"collectCoverage":false,"verbose":false,"bail":false}}}
12:01:09 (23493) DEBUG ConfigReader Loading config stryker.conf.js
12:01:09 (23493) DEBUG PluginLoader Loading plugins stryker-babel-transpiler (matched with expression stryker-*)
12:01:09 (23493) DEBUG PluginLoader Loading plugins stryker-html-reporter (matched with expression stryker-*)
12:01:09 (23493) DEBUG PluginLoader Loading plugins stryker-javascript-mutator (matched with expression stryker-*)
12:01:09 (23493) DEBUG PluginLoader Loading plugins stryker-jest-runner (matched with expression stryker-*)
12:01:09 (23493) DEBUG PluginLoader Loading plugins stryker-babel-transpiler
12:01:09 (23493) DEBUG PluginLoader Loading plugins stryker-html-reporter
12:01:09 (23493) DEBUG PluginLoader Loading plugins stryker-javascript-mutator
12:01:09 (23493) DEBUG PluginLoader Loading plugins stryker-jest-runner
12:01:09 (23493) DEBUG TestFrameworkOrchestrator The `coverageAnalysis` setting is "off", not hooking into the test framework to achieve performance benefits.
12:01:09 (23493) INFO InputFileResolver Found 569 of 1295 file(s) to be mutated.
12:01:09 (23493) DEBUG InputFileResolver All input files: [
all/filles
]
12:01:29 (23493) DEBUG Sandbox Creating a sandbox for files in path/to/project.stryker-tmp/sandbox7300381
12:01:29 (23493) DEBUG Sandbox Creating test runner 0 using settings {port: 9234}
12:01:29 (23493) DEBUG ChildProcessProxy Starting path/to/projectnode_modules/stryker/src/test-runner/ChildProcessTestRunnerWorker.js in child process 23527
12:01:34 (23493) DEBUG TimeoutDecorator Starting timeout timer (300000 ms) for a test run
12:01:30 (23527) DEBUG PluginLoader Loading stryker-* from path/to/projectnode_modules
12:01:30 (23527) DEBUG PluginLoader Loading plugins stryker-babel-transpiler (matched with expression stryker-*)
12:01:30 (23527) DEBUG PluginLoader Loading plugins stryker-html-reporter (matched with expression stryker-*)
12:01:30 (23527) DEBUG PluginLoader Loading plugins stryker-javascript-mutator (matched with expression stryker-*)
12:01:30 (23527) DEBUG PluginLoader Loading plugins stryker-jest-runner (matched with expression stryker-*)
12:01:30 (23527) DEBUG PluginLoader Loading plugins stryker-babel-transpiler
12:01:32 (23527) DEBUG PluginLoader Loading plugins stryker-html-reporter
12:01:33 (23527) DEBUG PluginLoader Loading plugins stryker-javascript-mutator
12:01:33 (23527) DEBUG PluginLoader Loading plugins stryker-jest-runner
12:01:33 (23527) DEBUG ChildProcessProxyWorker Changing current working directory for this process to path/to/project.stryker-tmp/sandbox7300381
12:01:34 (23527) DEBUG JestTestRunner Project root is path/to/project.stryker-tmp/sandbox7300381
12:01:34 (23527) TRACE JestPromiseTestAdapter Invoking Jest with config {"testRegex":"(<rootDir>/test/.*|)\\.spec\\.jsx?$","transform":{"^.+\\.js$":"babel-jest","^.+\\.graphql$":"<rootDir>/tools/jest/graphqlTransformer.js","\\.(txt|jpg|svg|png)$":"<rootDir>/tools/jest/fileTransformer.js"},"moduleNameMapper":{"\\.(css|less)$":"identity-obj-proxy"},"modulePathIgnorePatterns":["<rootDir>/build/"],"moduleFileExtensions":["js","json","graphql"],"snapshotSerializers":["enzyme-to-json/serializer"],"collectCoverageFrom":["src/**/*.js"],"coveragePathIgnorePatterns":["src/config/","src/flow/","src/graphql","src/styles","src/types","types.js","styles.js"],"coverageReporters":["cobertura","lcov","text","text-summary","json-summary"],"setupTestFrameworkScriptFile":"<rootDir>/tools/jest/setup-jasmine-env.js","setupFiles":["<rootDir>/tools/jest/setup-react-adapter.js"],"watchPlugins":["jest-watch-typeahead/filename","jest-watch-typeahead/testname"],"collectCoverage":false,"verbose":false,"bail":false,"rootDir":"path/to/project.stryker-tmp/sandbox7300381","reporters":[]}
12:04:07 (23493) DEBUG ChildProcessProxy Disposing of worker process 23527
12:04:07 (23493) DEBUG ChildProcessProxy Kill 23527
```

**Comment by simondel** [comment]
Thanks for opening this detailed issue!

Could you remove the following from your Stryker config and then try again?
```js
 transpilers: ['babel'],
 babelrcFile: '.babelrc',
```

**Comment by nicojs** [comment]
@eskimoblood 

> we use babel to compile the tests.

That is true, but it seems that Jest is responsible for that. You now configured both Stryker and Jest to transpile your code. Removing `transpilers` from your stryker config, should solve that problem.

**Comment by eskimoblood** [comment]
Still failing:

```
13:16:10 (69987) INFO ConfigReader Using stryker.conf.js in the current working directory.
13:16:10 (69987) DEBUG PluginLoader Loading stryker-* from path/to/Project/node_modules
13:16:10 (69987) DEBUG Stryker Using config: {"logLevel":"info","fileLogLevel":"trace","timeoutMS":5000,"timeoutFactor":1.5,"plugins":["stryker-*"],"port":9234,"reporter":[],"reporters":["clear-text","progress"],"coverageAnalysis":"off","testRunner":"jest","mutator":"javascript","transpilers":[],"maxConcurrentTestRunners":null,"symlinkNodeModules":true,"thresholds":{"high":80,"low":60,"break":null},"packageManager":"yarn","mutate":["src/**/*.js"],"configFile":"stryker.conf.js","jest":{"project":"default","config":{"testRegex":"(<rootDir>/test/.*|)\\.spec\\.jsx?$","transform":{"^.+\\.js$":"babel-jest","^.+\\.graphql$":"<rootDir>/tools/jest/graphqlTransformer.js","\\.(txt|jpg|svg|png)$":"<rootDir>/tools/jest/fileTransformer.js"},"moduleNameMapper":{"\\.(css|less)$":"identity-obj-proxy"},"modulePathIgnorePatterns":["<rootDir>/build/"],"moduleFileExtensions":["js","json","graphql"],"snapshotSerializers":["enzyme-to-json/serializer"],"collectCoverageFrom":["src/**/*.js"],"coveragePathIgnorePatterns":["src/config/","src/flow/","src/graphql","src/styles","src/types","types.js","styles.js"],"coverageReporters":["cobertura","lcov","text","text-summary","json-summary"],"setupTestFrameworkScriptFile":"<rootDir>/tools/jest/setup-jasmine-env.js","setupFiles":["<rootDir>/tools/jest/setup-react-adapter.js"],"watchPlugins":["jest-watch-typeahead/filename","jest-watch-typeahead/testname"],"collectCoverage":false,"verbose":false,"bail":false}}}
13:16:10 (69987) DEBUG ConfigReader Loading config stryker.conf.js
13:16:10 (69987) DEBUG PluginLoader Loading plugins stryker-javascript-mutator (matched with expression stryker-*)
13:16:10 (69987) DEBUG PluginLoader Loading plugins stryker-jest-runner (matched with expression stryker-*)
13:16:10 (69987) DEBUG PluginLoader Loading plugins stryker-javascript-mutator
13:16:10 (69987) DEBUG PluginLoader Loading plugins stryker-jest-runner
13:16:10 (69987) DEBUG TestFrameworkOrchestrator The `coverageAnalysis` setting is "off", not hooking into the test framework to achieve performance benefits.
13:16:10 (69987) INFO InputFileResolver Found 566 of 1296 file(s) to be mutated.
13:16:10 (69987) DEBUG InputFileResolver All input files: [ ...bunch of files]
13:16:10 (69987) DEBUG InputFileResolver Files to mutate: [ ...bunch of files]
13:16:10 (69987) INFO InitialTestExecutor Starting initial test run. This may take a while.
13:16:10 (69987) DEBUG Sandbox Creating a sandbox for files in path/to/Project/.stryker-tmp/sandbox8437683
13:16:11 (69987) DEBUG Sandbox Creating test runner 0 using settings {port: 9234}
13:16:11 (69987) DEBUG ChildProcessProxy Starting path/to/Project/node_modules/stryker/src/test-runner/ChildProcessTestRunnerWorker.js in child process 69989
13:16:12 (69989) DEBUG PluginLoader Loading stryker-* from path/to/Project/node_modules
13:16:12 (69989) DEBUG PluginLoader Loading plugins stryker-javascript-mutator (matched with expression stryker-*)
13:16:12 (69989) DEBUG PluginLoader Loading plugins stryker-jest-runner (matched with expression stryker-*)
13:16:12 (69989) DEBUG PluginLoader Loading plugins stryker-javascript-mutator
13:16:15 (69989) DEBUG PluginLoader Loading plugins stryker-jest-runner
13:16:15 (69989) DEBUG ChildProcessProxyWorker Changing current working directory for this process to path/to/Project/.stryker-tmp/sandbox8437683
13:16:15 (69989) DEBUG JestTestRunner Project root is path/to/Project/.stryker-tmp/sandbox8437683
13:16:15 (69987) DEBUG TimeoutDecorator Starting timeout timer (300000 ms) for a test run
13:16:15 (69989) TRACE JestPromiseTestAdapter Invoking Jest with config {"testRegex":"(<rootDir>/test/.*|)\\.spec\\.jsx?$","transform":{"^.+\\.js$":"babel-jest","^.+\\.graphql$":"<rootDir>/tools/jest/graphqlTransformer.js","\\.(txt|jpg|svg|png)$":"<rootDir>/tools/jest/fileTransformer.js"},"moduleNameMapper":{"\\.(css|less)$":"identity-obj-proxy"},"modulePathIgnorePatterns":["<rootDir>/build/"],"moduleFileExtensions":["js","json","graphql"],"snapshotSerializers":["enzyme-to-json/serializer"],"collectCoverageFrom":["src/**/*.js"],"coveragePathIgnorePatterns":["src/config/","src/flow/","src/graphql","src/styles","src/types","types.js","styles.js"],"coverageReporters":["cobertura","lcov","text","text-summary","json-summary"],"setupTestFrameworkScriptFile":"<rootDir>/tools/jest/setup-jasmine-env.js","setupFiles":["<rootDir>/tools/jest/setup-react-adapter.js"],"watchPlugins":["jest-watch-typeahead/filename","jest-watch-typeahead/testname"],"collectCoverage":false,"verbose":false,"bail":false,"rootDir":"path/to/Project/.stryker-tmp/sandbox8437683","reporters":[]}
13:16:55 (69987) TRACE ChildProcessProxy (node:69989) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'then' of undefined

13:16:55 (69987) TRACE ChildProcessProxy (node:69989) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:69989) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'then' of undefined

13:17:50 (69987) TRACE ChildProcessProxy (node:69989) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): TypeError: resetField is not a function

13:19:18 (69987) DEBUG ChildProcessProxy Disposing of worker process 69989
13:19:18 (69987) DEBUG ChildProcessProxy Kill 69989
```

**Comment by nicojs** [comment]
Still failing, but with a different error: `UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'then' of undefined`

Just to be sure, you're still using jest 23, right? Jest 21 is not supported and will result in this error (or something simular).

Would it be possible to make a small repository to reproduce this issue? It seems that something is wrong in the stryker-jest-runner plugin.

**Comment by simondel** [comment]
Hi @eskimoblood is there something we can do to help you with this issue?

**Comment by simondel** [comment]
We're closing this issue for now. Feel free to open it if you still have it with Stryker v1
