### ISSUE TITLE
Stryker fails when Jest has it.skip() tests

### ISSUE THREAD

**Issue by Chowarmaan** [stryker-mutator/stryker#1152]
### Summary
In my test suite, I have a test that is marked to be skipped using the it.skip() syntax.  When Stryker is analyzing this test, it determines that the test had initial test failures, where the skipped tests are not failures, but should be ignored.
```
10:43:06 (17232) ERROR InitialTestExecutor One or more tests failed in the initial test run:
        Test the root path It should response the GET method
10:43:06 (17232) ERROR StrykerCli an error occurred Error: There were failed tests in the initial test run.
    at InitialTestExecutor.validateResult (C:\Users\stevens\Development\TestScripts\Emulator\node_modules\stryker\src\process\InitialTestExecutor.js:108:27)
    at InitialTestExecutor.<anonymous> (C:\Users\stevens\Development\TestScripts\Emulator\node_modules\stryker\src\process\InitialTestExecutor.js:45:30)
    at step (C:\Users\stevens\Development\TestScripts\Emulator\node_modules\tslib\tslib.js:133:27)
    at Object.next (C:\Users\stevens\Development\TestScripts\Emulator\node_modules\tslib\tslib.js:114:57)
    at fulfilled (C:\Users\stevens\Development\TestScripts\Emulator\node_modules\tslib\tslib.js:104:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Stryker config

```js
module.exports = function (config) {
	config.set({
		coverageAnalysis: "off",
		htmlReporter: {
			baseDir: 'docs/mutation'
		},
		jest: {
			config: require('./jest.config.js'),
			projectType: 'custom'
		},
		loglevel: "debug",
		mutate: [
			'src/**/*.ts',
			'!src/**/*.spec.ts'
		],
		mutator: {
			name: "typescript",
			excludedMutations: []
		},
		packageManager: "npm",
		reporters: ["html", "progress"],
		testRunner: "jest",
		transpilers: [],
		tsconfigFile: "tsconfig.json"
	});
};
```

### Stryker environment

```
+-- stryker@0.29.2
+-- stryker-api@0.21.1
+-- stryker-cli@0.2.0
+-- stryker-html-reporter@0.16.2
+-- stryker-jest-runner@1.2.1
+-- stryker-typescript@0.14.0
```

```
+-- @types/jest@23.3.2
+-- jest@23.6.0
| `-- jest-cli@23.6.0
```

### Your Environment

| software         | version(s)
| ---------------- | -------  
| node             | 10.10.0
| npm              | 6.4.1
| Operating System | Windows 10

### Add stryker.log

[stryker.log](https://github.com/stryker-mutator/stryker/files/2401817/stryker.log)

**Comment by Archcry** [comment]
Do you have a repository to reproduce this issue bynany chance. That'll help us to more easily resolve this issue.

**Comment by Chowarmaan** [comment]
I can create one, but you just need to simply add a test with it.skip() and
expect(true).toBeTruthy() will show the issue.

**Comment by Archcry** [comment]
I was able to reproduce this issue with some random jest project I found online. I'll fix it tonight.
