### ISSUE TITLE
Jest v24 with Flow failed to execute by Stryker

### ISSUE THREAD

**Issue by vpanichkin** [stryker-mutator/stryker#1350]
### Steps to reproduce:

1) Install Jest v24.0.0
2) Run stryker

After updating Jest, **babel-preset-flow** stop working while patching the babel by striker. 

My observations: 
1)  I have tried updating to babel@7.0.0-bridge.0, although it haven't solved an issue.
2)  Moreover, unit-tests that are run with jest directly are transpiled properly with **babel-preset-flow** and work without any problems.

Please update stryker to be compatible with Jest v24.0.0

### Error Summary

```
    SyntaxError: Unexpected token (3:12)

      1 | // @flow
      2 |
    >3 | import type { tag } from '../../tag-module';
         |           ^
      4 |
      5 | module.exports = parsedTag;
      6 |


      at Parser.raise (../../node_modules/@babel/parser/lib/index.js:3831:17)
      at Parser.unexpected (../../node_modules/@babel/parser/lib/index.js:5143:16)
      at Parser.expectContextual (../../node_modules/@babel/parser/lib/index.js:5115:41)
      at Parser.parseImport (../../node_modules/@babel/parser/lib/index.js:8565:12)
      at Parser.parseStatementContent (../../node_modules/@babel/parser/lib/index.js:7338:27)
      at Parser.parseStatement (../../node_modules/@babel/parser/lib/index.js:7248:17)
      at Parser.parseBlockOrModuleBlockBody (../../node_modules/@babel/parser/lib/index.js:7812:25)
      at Parser.parseBlockBody (../../node_modules/@babel/parser/lib/index.js:7799:10)
      at Parser.parseTopLevel (../../node_modules/@babel/parser/lib/index.js:7181:10)
      at Parser.parse (../../node_modules/@babel/parser/lib/index.js:8660:17)

(9064) ERROR StrykerCli an error occurred Error: Something went wrong in the initial test run
    at InitialTestExecutor.validateResult (..\node_modules\stryker\src\process\InitialTestExecutor.js:125:15)
    at InitialTestExecutor.<anonymous> (..\node_modules\stryker\src\process\InitialTestExecutor.js:45:30)
    at step (..\node_modules\tslib\tslib.js:133:27)
    at Object.next (..\node_modules\tslib\tslib.js:114:57)
    at fulfilled (..\node_modules\tslib\tslib.js:104:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Stryker config

```
module.exports = function(config){
  config.set({
  babelrcFile: '.babelrc',
  coverageAnalysis: 'off',
  htmlReporter: { baseDir: 'coverage/mutation' },
  mutator: 'javascript',
  testRunner: 'jest',
  transpilers: ['babel'],
  reporters: ['html', 'clear-text', 'progress'],
  packageManager: 'yarn',
  mutate: [
    'src/app/**/*.js',
    '!src/app/**/*.test.js',
    '!**/enum/**/*.js',
  ],
  files: ['src/**/*.js'],
  thresholds: {
    high: 98,
    low: 98,
    break: 98,
  },
  });
}
```
### .babelrc config

```
{
  "presets": ["flow"]
}

```
### Stryker environment

```
    "stryker": "^0.34.0",
    "stryker-api": "^0.23.0",
    "stryker-babel-transpiler": "^0.8.0",
    "stryker-html-reporter": "^0.17.0",
    "stryker-javascript-mutator": "^0.13.0",
    "stryker-jest-runner": "^1.3.0"
```

```
    "jest": "^24.0.0",
    "babel-cli": "^6.26.0",
    "babel-eslint": "^8.0.3",
    "babel-preset-flow": "^6.23.0",
    "babel-core": "^6.26.3",
```

### Your Environment

| software         | version(s)
| ---------------- | -------  
| node             |  v10.11.0
| npm              |  v6.4.1
| Operating System |  Win10 x64

### Add stryker.log

```
15:31:08 (21612) DEBUG PluginLoader Loading stryker-* from <rootDirObfuscated>\node_modules
15:31:08 (21612) DEBUG ConfigReader Loading config test/mutation/build/stryker.conf.js
15:31:08 (21612) DEBUG Stryker Using config: {"mutate":["src/app/**/*.js","!src/app/**/*.test.js","!**/enum/**/*.js"],"logLevel":"info","fileLogLevel":"trace","timeoutMS":5000,"timeoutFactor":1.5,"plugins":["stryker-*"],"port":9234,"reporter":[],"reporters":["html","clear-text","progress"],"coverageAnalysis":"off","testRunner":"jest","mutator":"javascript","transpilers":["babel"],"maxConcurrentTestRunners":null,"symlinkNodeModules":true,"thresholds":{"high":98,"low":98,"break":98},"allowConsoleColors":true,"babelrcFile":".babelrc","htmlReporter":{"baseDir":"coverage/mutation"},"packageManager":"yarn","files":[<rootDirObfuscated>\\app\\**\\*.js"],"configFile":"test/mutation/build/stryker.conf.js","jest":{"projectType":"custom","config":{"testEnvironment":"node","verbose":false,"transform":{"^.+\\.jsx?$":"babel-jest"},"roots":["<rootDirObfuscated>/src/app"],"collectCoverageFrom":["src/app/**/*.js"],"coverageDirectory":"./coverage/unit-test","coverageThreshold":{"global":{"branches":97,"functions":100,"lines":100,"statements":100}},"collectCoverage":false,"bail":false}}}
15:31:08 (21612) DEBUG PluginLoader Loading plugins stryker-babel-transpiler (matched with expression stryker-*)
15:31:08 (21612) DEBUG PluginLoader Loading plugins stryker-html-reporter (matched with expression stryker-*)
15:31:08 (21612) DEBUG PluginLoader Loading plugins stryker-javascript-mutator (matched with expression stryker-*)
15:31:08 (21612) DEBUG PluginLoader Loading plugins stryker-jest-runner (matched with expression stryker-*)
15:31:08 (21612) DEBUG PluginLoader Loading plugins stryker-babel-transpiler
15:31:08 (21612) DEBUG PluginLoader Loading plugins stryker-html-reporter
15:31:08 (21612) DEBUG PluginLoader Loading plugins stryker-javascript-mutator
15:31:08 (21612) DEBUG PluginLoader Loading plugins stryker-jest-runner
15:31:08 (21612) INFO ReporterOrchestrator Detected that current console does not support the "progress" reporter, downgrading to "progress-append-only" reporter
15:31:08 (21612) DEBUG TestFrameworkOrchestrator The `coverageAnalysis` setting is "off", not hooking into the test framework to achieve performance benefits.
15:31:09 (21612) INFO InputFileResolver Found 52 of 112 file(s) to be mutated.
15:31:09 (21612) DEBUG InputFileResolver All input files: [
<filesListObfuscated>
]
15:31:09 (21612) DEBUG InputFileResolver Files to mutate: [
 <filesListObfuscated>
]
15:31:10 (21612) DEBUG Sandbox Creating a sandbox for files in <rootDirObfuscated>\.stryker-tmp\sandbox9864229
15:31:10 (21612) DEBUG Sandbox Creating test runner 0 using settings {port: 9234}
15:31:10 (21612) DEBUG ChildProcessProxy Starting <rootDirObfuscated>\node_modules\stryker\src\test-runner\ChildProcessTestRunnerWorker.js in child process 14656
15:31:10 (21612) DEBUG TimeoutDecorator Starting timeout timer (300000 ms) for a test run
15:31:10 (14656) DEBUG PluginLoader Loading stryker-* from <rootDirObfuscated>\node_modules
15:31:10 (14656) DEBUG PluginLoader Loading plugins stryker-babel-transpiler (matched with expression stryker-*)
15:31:10 (14656) DEBUG PluginLoader Loading plugins stryker-html-reporter (matched with expression stryker-*)
15:31:10 (14656) DEBUG PluginLoader Loading plugins stryker-javascript-mutator (matched with expression stryker-*)
15:31:10 (14656) DEBUG PluginLoader Loading plugins stryker-jest-runner (matched with expression stryker-*)
15:31:10 (14656) DEBUG PluginLoader Loading plugins stryker-babel-transpiler
15:31:10 (14656) DEBUG PluginLoader Loading plugins stryker-html-reporter
15:31:10 (14656) DEBUG PluginLoader Loading plugins stryker-javascript-mutator
15:31:10 (14656) DEBUG PluginLoader Loading plugins stryker-jest-runner
15:31:10 (14656) DEBUG ChildProcessProxyWorker Changing current working directory for this process to <rootDirObfuscated>\.stryker-tmp\sandbox9864229
15:31:10 (14656) DEBUG JestTestRunner Running jest with --findRelatedTests flag. Set jest.enableFindRelatedTests to false to run all tests on every mutant.
15:31:10 (14656) DEBUG JestTestRunner Project root is <rootDirObfuscated>\.stryker-tmp\sandbox9864229
15:31:10 (14656) TRACE JestPromiseTestAdapter Invoking Jest with config {"testEnvironment":"node","verbose":false,"transform":{"^.+\\.jsx?$":"babel-jest"},"roots":["<fileDirObfuscated>"],"collectCoverageFrom":["src/app/**/*.js"],"coverageDirectory":"./coverage/unit-test","coverageThreshold":{"global":{"branches":97,"functions":100,"lines":100,"statements":100}},"collectCoverage":false,"bail":false,"rootDir":"<rootDirObfuscated>\\.stryker-tmp\\sandbox9864229","reporters":[]}
15:31:14 (21612) DEBUG ChildProcessProxy Disposing of worker process 14656
15:31:14 (21612) DEBUG ChildProcessProxy Kill 14656
```

**Comment by wips** [comment]
Yep, we're having the same issue

**Comment by nicojs** [comment]
Thanks for reporting. Our babel transpiler plugin is still on v6. Migrating it now. We'll probably be doing a release later this week/next week so we should be able to sneak v7 support in there. 👍

**Comment by nicojs** [comment]
Hmm could you try this again? I was too quick to draw conclusions. I think we should update our `javascript-mutator`. @simondel  what do you think?

**Comment by simondel** [comment]
I think this should already be fixed by now. You can now also specify a set of plugins for the javascript mutator: https://www.npmjs.com/package/@stryker-mutator/javascript-mutator
