### ISSUE TITLE
Performance tests are unstable

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker#1503]
The build on master fails sometimes on the performance tests:
```
/home/travis/build/stryker-mutator/stryker/perf/node_modules/ts-node/src/index.ts:228
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
tasks/run-perf-tests.ts(1,21): error TS7016: Could not find a declaration file for module 'mz/fs'. '/home/travis/build/stryker-mutator/stryker/node_modules/mz/fs.js' implicitly has an 'any' type.
  Try `npm install @types/mz` if it exists or add a new declaration (.d.ts) file containing `declare module 'mz/fs';`
    at createTSError (/home/travis/build/stryker-mutator/stryker/perf/node_modules/ts-node/src/index.ts:228:12)
    at getOutput (/home/travis/build/stryker-mutator/stryker/perf/node_modules/ts-node/src/index.ts:334:40)
    at Object.compile (/home/travis/build/stryker-mutator/stryker/perf/node_modules/ts-node/src/index.ts:367:11)
    at Module.m._compile (/home/travis/build/stryker-mutator/stryker/perf/node_modules/ts-node/src/index.ts:413:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/travis/build/stryker-mutator/stryker/perf/node_modules/ts-node/src/index.ts:416:12)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at Object.<anonymous> (/home/travis/build/stryker-mutator/stryker/perf/node_modules/ts-node/src/bin.ts:151:12)
```

Source: https://travis-ci.org/stryker-mutator/stryker/jobs/521282433

**Comment by simondel** [comment]
Fixed by #1507
