### ISSUE TITLE
ttypescript support

### ISSUE THREAD

**Issue by Djaler** [stryker-mutator/stryker#1590]
I use [ttypescript](https://github.com/cevek/ttypescript) with [ts-transformer-keys](https://github.com/kimamula/ts-transformer-keys) plugin in my tests. And it works correctly with Jest. I just need to specify the compiler:
```
globals: {
        'ts-jest': {
            compiler: 'ttypescript',
            tsConfig: 'tsconfig.test.json',
        },
    },
```
But this doesn't work with stryker:
`TypeError: ts_transformer_keys_1.keys is not a function`
Is there a way to override typescript compiler in Stryker?

Documentation about ts-jest: https://kulshekhar.github.io/ts-jest/user/config/compiler

**Comment by nicojs** [comment]
Well, we just run jest as you would via the command line. No smart integration there. Maybe the problem is at parse & mutate time? Could you attach a stryker.log file to this issue? Thanks

**Comment by Djaler** [comment]
There are nothing interesting. But this is what I have in the output:
```
12:17:14 (17254) DEBUG JestTestRunner Running jest with --findRelatedTests flag. Set jest.enableFindRelatedTests to false to run all tests on every mutant.
12:17:14 (17254) DEBUG JestTestRunner Project root is /home/kromanov/Projects/js-utils/.stryker-tmp/sandbox9432237
12:17:14 (17237) DEBUG TimeoutDecorator Starting timeout timer (300000 ms) for a test run
12:17:26 (17237) DEBUG ChildProcessProxy Disposing of worker process 17254
12:17:26 (17237) DEBUG ChildProcessProxy Kill 17254
12:17:26 (17237) ERROR InitialTestExecutor One or more tests failed in the initial test run:
        isPaginationChanged should return true if any field of pagination was changed encountered a declaration exception
                TypeError: ts_transformer_keys_1.keys is not a function
    at Suite.describe (/home/kromanov/Projects/js-utils/.stryker-tmp/sandbox9432237/tests/pagination.spec.ts:46:34)
    at addSpecsToSuite (/home/kromanov/Projects/js-utils/node_modules/jest-jasmine2/build/jasmine/Env.js:417:49)
    at Env.describe (/home/kromanov/Projects/js-utils/node_modules/jest-jasmine2/build/jasmine/Env.js:387:9)
    at describe (/home/kromanov/Projects/js-utils/node_modules/jest-jasmine2/build/jasmine/jasmineLight.js:81:18)
    at Suite.Object.<anonymous>.describe (/home/kromanov/Projects/js-utils/.stryker-tmp/sandbox9432237/tests/pagination.spec.ts:45:5)
    at addSpecsToSuite (/home/kromanov/Projects/js-utils/node_modules/jest-jasmine2/build/jasmine/Env.js:417:49)
    at Env.describe (/home/kromanov/Projects/js-utils/node_modules/jest-jasmine2/build/jasmine/Env.js:387:9)
    at describe (/home/kromanov/Projects/js-utils/node_modules/jest-jasmine2/build/jasmine/jasmineLight.js:81:18)
    at Object.<anonymous> (/home/kromanov/Projects/js-utils/.stryker-tmp/sandbox9432237/tests/pagination.spec.ts:44:1)
    at Runtime._execModule (/home/kromanov/Projects/js-utils/node_modules/jest-runtime/build/index.js:765:13)
    at Runtime.requireModule (/home/kromanov/Projects/js-utils/node_modules/jest-runtime/build/index.js:361:14)
    at /home/kromanov/Projects/js-utils/node_modules/jest-jasmine2/build/index.js:202:13
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/kromanov/Projects/js-utils/node_modules/jest-jasmine2/build/index.js:27:24)
    at _next (/home/kromanov/Projects/js-utils/node_modules/jest-jasmine2/build/index.js:47:9)
    at /home/kromanov/Projects/js-utils/node_modules/jest-jasmine2/build/index.js:52:7
    at new Promise (<anonymous>)
    at /home/kromanov/Projects/js-utils/node_modules/jest-jasmine2/build/index.js:44:12
    at jasmine2 (/home/kromanov/Projects/js-utils/node_modules/jest-jasmine2/build/index.js:60:19)
    at /home/kromanov/Projects/js-utils/node_modules/jest-runner/build/runTest.js:383:24
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/kromanov/Projects/js-utils/node_modules/jest-runner/build/runTest.js:161:24)
    at _next (/home/kromanov/Projects/js-utils/node_modules/jest-runner/build/runTest.js:181:9)
12:17:26 (17237) ERROR StrykerCli an error occurred Error: There were failed tests in the initial test run.
    at InitialTestExecutor.validateResult (/home/kromanov/Projects/js-utils/node_modules/@stryker-mutator/core/src/process/InitialTestExecutor.js:68:27)
    at InitialTestExecutor.run (/home/kromanov/Projects/js-utils/node_modules/@stryker-mutator/core/src/process/InitialTestExecutor.js:40:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by Djaler** [comment]
I tried to run tests manually in `.styker-tmp/sandbox123` and they fail too. But they works when I run them outside the sandbox

**Comment by nicojs** [comment]
> There are nothing interesting. 

I'll be the judge of that 😅 

This is really interesting. The error does occur in the test runner part. As far as I know, the `@stryker-mutator/jest-runner` requires you to "bring your own jest", so I would expact that to work. 

Would it be possible to create a small reproduction repository that illustrates this issue? That is usally the fasted way for us to fix issues like this, because the wide range of javascript project structures out there. 

You can either create a small github repo, but a zipfile attatched to this issue is also fine.

> I tried to run tests manually in `.stryker-tmp/sandbox123` and they fail too. But they works when I run them outside the sandbox

Interesting. It might to do with the symlinked node_modules. For some reason, Jest is really dependent on the node_modules being right next to your project.

**Comment by Djaler** [comment]
> I'll be the judge of that

I mean that I see nothing interesting in log file. Trace that I send you is from terminal output

**Comment by nicojs** [comment]
Yeah, terminal and logfile have the same output. No worries, I just found it a bit funny.

A small repro repo should help us to find the issue.

**Comment by Djaler** [comment]
https://github.com/Djaler/stryker-jest-ttypescript-bug-example

**Comment by nicojs** [comment]
I'm getting the same error from jest directly 🤷‍♀️

```
$ npm t

> stryker-jest-ttypescript-example@1.0.0 test C:\z\github\Djaler\stryker-jest-ttypescript-bug-example
> jest

 FAIL  tests/main.spec.ts
  × test (5ms)

  ● test

    TypeError: ts_transformer_keys_1.keys is not a function

      3 |
      4 | test('test', () => {
    > 5 |     const interfaceKeys = keys<SomeInterface>();
        |                           ^
      6 |
      7 |     console.log(interfaceKeys);
      8 |

      at Object.<anonymous>.test (tests/main.spec.ts:5:27)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        4.378s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

**Comment by Djaler** [comment]
@nicojs Sorry, fixed it. Check latest commit

**Comment by Djaler** [comment]
@nicojs, can you check it? ^

**Comment by mauricedb** [comment]
@Djaler, You are using an old version of Stryker and need to set the `tempDirName` setting in your `stryker.conf.js`.

See [here](https://github.com/Djaler/stryker-jest-ttypescript-bug-example/pull/1) for a PR that fixes the error in your sample.

**Comment by Djaler** [comment]
Yeah, looks like this work well with renamed temp directory. Thanks
