### ISSUE TITLE
Error with simple Mocha test

### ISSUE THREAD

**Issue by c0ncentus** [stryker-mutator/stryker#1619]
Hello, I completly not understand why strykker have this pattern "test/**/*.js" 
1 im in  typescript config 
2 I search on all my project this pattern, no match on all my project...
3 all i want is a simplest way to test stryker on my preference setting ... 

### Stryker config

```js
{
    "compilerOptions": {
        "module": "commonjs",
        "noImplicitAny": true,
        "removeComments": true,
        "preserveConstEnums": true,
        "sourceMap": true
    },
    "include": [
        "src/*.ts",
        "Test/*.spec.ts"
    ],
    "exclude": [
        "node_modules"
    ]
}
```

### Stryker environment

```
    "@stryker-mutator/core": "^2.0.0",
    "@stryker-mutator/html-reporter": "^2.0.0",
    "@stryker-mutator/mocha-framework": "^2.0.0",
    "@stryker-mutator/mocha-runner": "^2.0.0",
    "@stryker-mutator/typescript": "^2.0.0",
    "stryker-html-reporter": "^0.18.1",
    "stryker-mocha-runner": "^0.17.1",
```

```
    "@types/mocha": "^5.2.7",
    "mocha": "^6.1.4"
```

### Test runner environment

```
nyc -r lcov -e .ts -x \"*.spec.ts\" mocha -r ts-node/register Test/*.spec.ts && nyc report
```

Tsconfig
```
{
    "compilerOptions": {
        "module": "commonjs",
        "noImplicitAny": true,
        "removeComments": true,
        "preserveConstEnums": true,
        "sourceMap": true
    },
    "include": [
        "src/*.ts",
        "Test/*.spec.ts"
    ],
    "exclude": [
        "node_modules"
    ]
}
```

### Your Environment

| software         | version(s)
| ---------------- | -------  
| node             | v10.15.3
| npm              | 6.9.2
| Operating System | Windows 10

```
### Add stryker.log
```
```
08:10:54 (10828) INFO ConfigReader Using stryker.conf.js in the current working directory.
08:10:54 (10828) INFO InputFileResolver Found 1 of 1 file(s) to be mutated.
08:10:54 (10828) INFO InitialTestExecutor Starting initial test run. This may take a while.
08:10:54 (10828) ERROR StrykerCli an error occurred Error: Error: [MochaTestRunner] No files discovered
(tried pattern(s) [
  "test/**/*.js"
]). Please specify the files (glob patterns) containing your tests in mochaOptions.files in your stryker.conf.js file.
Error: [MochaTestRunner] No files discovered (tried pattern(s) [
  "test/**/*.js"
]). Please specify the files (glob patterns) containing your tests in mochaOptions.files in your stryker.conf.js file.
    at MochaTestRunner.init (C:\Users\Martin\Desktop\fire\node_modules\stryker-mocha-runner\src\MochaTestRunner.js:28:19)
    at ChildProcessTestRunnerWorker.init (C:\Users\Martin\Desktop\fire\node_modules\@stryker-mutator\core\src\test-runner\ChildProcessTestRunnerWorker.js:15:45)
    at ChildProcessProxyWorker.doCall (C:\Users\Martin\Desktop\fire\node_modules\@stryker-mutator\core\src\child-proxy\ChildProcessProxyWorker.js:74:56)
    at resolve (C:\Users\Martin\Desktop\fire\node_modules\@stryker-mutator\core\src\child-proxy\ChildProcessProxyWorker.js:46:53)
    at new Promise (<anonymous>)
    at ChildProcessProxyWorker.handleMessage (C:\Users\Martin\Desktop\fire\node_modules\@stryker-mutator\core\src\child-proxy\ChildProcessProxyWorker.js:46:17)
    at process.emit (events.js:189:13)
    at emit (internal/child_process.js:820:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at ChildProcess.worker.on (C:\Users\Martin\Desktop\fire\node_modules\@stryker-mutator\core\src\child-proxy\ChildProcessProxy.js:100:68)
    at ChildProcess.emit (events.js:189:13)
    at emit (internal/child_process.js:820:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
08:10:54 (10828) INFO StrykerCli Trouble figuring out what went wrong? Try `npx stryker run --fileLogLevel trace --logLevel debug` to get some more info.
```

**Comment by c0ncentus** [comment]
https://github.com/stryker-mutator/stryker/issues/704 i will see this maybe i done with that

**Comment by nicojs** [comment]
Hi @c0ncentus you got it fixed? Have fun mutation testing! 👽
