### ISSUE TITLE
RuntimeError: memory access out of bounds on typescript + mocha

### ISSUE THREAD

**Issue by peternedap** [stryker-mutator/stryker#1690]
**Summary**

When running Stryker on a typescript project I get the following error message: 

```
$ stryker run
16:00:09 (924) INFO ConfigReader Using stryker.conf.js in the current working directory.
16:00:09 (924) INFO TypescriptConfigEditor Loading tsconfig file /project/tsconfig.json
16:00:09 (924) INFO InputFileResolver Found 9 of 27 file(s) to be mutated.
16:00:09 (924) INFO InitialTestExecutor Starting initial test run. This may take a while.
16:00:16 (924) INFO InitialTestExecutor Initial test run succeeded. Ran 145 tests in 6 seconds (net 273 ms, overhead 475 ms).
16:00:19 (924) INFO MutatorFacade 4027 Mutant(s) generated (62 Mutant(s) excluded)
16:00:25 (924) ERROR StrykerCli an error occurred RuntimeError: memory access out of bounds
    at wasm-function[18]:1732
    at wasm-function[28]:81
    at BasicSourceMapConsumer._parseMappings (/project/node_modules/@stryker-mutator/core/node_modules/source-map/lib/source-map-consumer.js:335:44)
    at BasicSourceMapConsumer._getMappingsPtr (/project/node_modules/@stryker-mutator/core/node_modules/source-map/lib/source-map-consumer.js:315:12)
    at _wasm.withMappingCallback (/project/node_modules/@stryker-mutator/core/node_modules/source-map/lib/source-map-consumer.js:665:14)
    at Object.withMappingCallback (/project/node_modules/@stryker-mutator/core/node_modules/source-map/lib/wasm.js:95:11)
    at BasicSourceMapConsumer.generatedPositionFor (/project/node_modules/@stryker-mutator/core/node_modules/source-map/lib/source-map-consumer.js:663:16)
    at SourceMap.generatedPositionFor (/project/node_modules/@stryker-mutator/core/src/transpiler/SourceMapper.js:204:57)
16:00:25 (924) INFO StrykerCli Trouble figuring out what went wrong? Try `npx stryker run --fileLogLevel trace --logLevel debug` to get some more info.
```
I have another project with the same configuration that does not give this error.

**Stryker config**

```js
module.exports = function(config) {
    config.set({
      mutator: {
          name: "typescript",
          excludedMutations: ["StringLiteral"],
      },
      transpilers: ["typescript"],
      tsconfigFile: "tsconfig.json",
      mutate: ["lib/**/*.ts"],
      reporters: ["clear-text", "progress"],
      testFramework: 'mocha',
      coverageAnalysis: "perTest",
      testRunner: "mocha",
      mochaOptions: {
          files: "dist/**/*.test.js"
      },
      packageManager: "yarn",
    });
  };
```

**Stryker environment**

```
├─ @stryker-mutator/api@2.0.2
├─ @stryker-mutator/core@2.0.2
│  ├─ @stryker-mutator/api@^2.0.2
│  ├─ @stryker-mutator/util@^2.0.2
├─ @stryker-mutator/html-reporter@1.3.1
│  ├─ @stryker-mutator/api@^1.3.1
│  ├─ @stryker-mutator/api@1.3.1
│  ├─ @stryker-mutator/util@^1.3.1
│  ├─ @stryker-mutator/util@1.3.1
├─ @stryker-mutator/mocha-framework@2.0.2
│  └─ @stryker-mutator/api@^2.0.2
├─ @stryker-mutator/mocha-runner@2.0.2
│  ├─ @stryker-mutator/api@^2.0.2
├─ @stryker-mutator/typescript@2.0.2
│  ├─ @stryker-mutator/api@^2.0.2
│  ├─ @stryker-mutator/util@^2.0.2
├─ @stryker-mutator/util@2.0.2
├─ stryker-cli@1.0.0
```

```
+-- mocha@2.0.2
```

**Your Environment**

| software         | version(s)
| ---------------- | -------  
| node             |  v11.8.0
| yarn              |  1.13.0
| Operating System | Ubuntu 18.04.3 LTS

**Add stryker.log**
[stryker.log](https://github.com/stryker-mutator/stryker/files/3555967/stryker.log)

**Comment by simondel** [comment]
Thanks for opening this issue! Is your project open source by any chance?

And how many mutants are generated on the successful project?

**Comment by peternedap** [comment]
Unfortunately, it isn't open source.
The successful project only generates 364 mutants

**Comment by peternedap** [comment]
Some more information: It seems like 2782 of the mutations happen in a single file. When excluding this file (thus leaving 1245 mutants) Stryker is able to run successfully.

**Comment by peternedap** [comment]
It seems like there is some kind of upper limit to the `.js.map` files of about 40,000 characters. Stryker is able to run successfully when deleting enough code to remain under this limit.

**Comment by simondel** [comment]
@nicojs didn't we introduce a pushback mechanism on the transpiled mutants a while back to prevent a memory overflow?

**Comment by peternedap** [comment]
I've created an example which also throws a `RuntimeError: memory access out of bounds` at https://github.com/peternedap/stryker_memory_bug, though I suspect it is caused by more than 511 branches in `Broken.ts` in this case. Removing line 517 makes Stryker run the tests properly (but still hang on the reporting step).

**Comment by simondel** [comment]
I belive this is fixed with `@stryker-mutator/core` version 2.2.0. I'm closing this issue for now. If you still have problems with the latest version, could you let me know/reopen the issue?

**Comment by peternedap** [comment]
Upgrading to 2.2.0 did fix the example code, but in my larger (unfortunately not open source) project I still get this error:

```
08:56:08 (8914) ERROR StrykerCli an error occurred RuntimeError: memory access out of bounds
    at wasm-function[18]:0xf76
    at wasm-function[28]:0x3494
    at BasicSourceMapConsumer._parseMappings (/home/peter/Documents/workspace/geometry/node_modules/@stryker-mutator/core/node_modules/source-map/lib/source-map-consumer.js:335:44)
    at BasicSourceMapConsumer._getMappingsPtr (/home/peter/Documents/workspace/geometry/node_modules/@stryker-mutator/core/node_modules/source-map/lib/source-map-consumer.js:315:12)
    at /home/peter/Documents/workspace/geometry/node_modules/@stryker-mutator/core/node_modules/source-map/lib/source-map-consumer.js:665:14
    at Object.withMappingCallback (/home/peter/Documents/workspace/geometry/node_modules/@stryker-mutator/core/node_modules/source-map/lib/wasm.js:95:11)
    at BasicSourceMapConsumer.generatedPositionFor (/home/peter/Documents/workspace/geometry/node_modules/@stryker-mutator/core/node_modules/source-map/lib/source-map-consumer.js:663:16)
    at SourceMap.generatedPositionFor (/home/peter/Documents/workspace/geometry/node_modules/@stryker-mutator/core/src/transpiler/SourceMapper.js:204:57)
    at async TranspiledSourceMapper.transpiledLocationFor (/home/peter/Documents/workspace/geometry/node_modules/@stryker-mutator/core/src/transpiler/SourceMapper.js:54:23)
    at async MutantTestMatcher.enrichWithCoveredTests (/home/peter/Documents/workspace/geometry/node_modules/@stryker-mutator/core/src/mutants/MutantTestMatcher.js:41:36)
```

**Comment by simondel** [comment]
Hi! I'm closing this issue for now. If it still persists with Stryker version 4, please open a new issue. Thanks!
