### ISSUE TITLE
inconsistency in e2e tests

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1759]
I have noticed the same issue in 3 DIFFERENT PRs about e2e tests (all 3 are failing in the same place, while they are completely different PRs so it shouldn't happen [one is passing e2e tho {the 4th one}])

**Comment by nicojs** [comment]
This mostely has to do with #1749, which we've mitigated for now (swept under the rug, see issue for more details).

However there is still a problem with the grunt integration test:

```
16:29:04 (5175) INFO InitialTestExecutor Starting initial test run. This may take a while.
16:29:04 (5175) WARN ChildProcessProxy Child process [pid 5221] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
	internal/process/main_thread_only.js:29
	    binding.chdir(directory);
	            ^
	
	Error: ENOENT: no such file or directory, chdir '/home/runner/work/stryker/stryker/e2e/test/grunt-stryker-test' -> '/home/runner/work/stryker/stryker/e2e/test/grunt-stryker-test/.stryker-tmp/sandbox3039564'
	    at process.chdir (internal/process/main_thread_only.js:29:13)
	    at process.chdir (/home/runner/work/stryker/stryker/e2e/node_modules/@stryker-mutator/core/node_modules/graceful-fs/polyfills.js:20:9)
	    at ChildProcessProxyWorker.handleMessage (/home/runner/work/stryker/stryker/e2e/node_modules/@stryker-mutator/core/src/child-proxy/ChildProcessProxyWorker.js:39:29)
	    at process.emit (events.js:210:5)
	    at emit (internal/child_process.js:876:12)
	    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
	  errno: -2,
```

It runs stryker twice with different configs. I think the first run is conflicting with the second one. For some reason the `.stryker-tmp` directory is deleted by the first run while the second one started. We can mitigate this by configuring a different temp dir.
