### ISSUE TITLE
Stryker crashes although jest running perfectly - something with TimeOut?

### ISSUE THREAD

**Issue by aviadavi** [stryker-mutator/stryker#1942]
**Summary**

Getting the below error
```
21:03:52 (11320) ERROR InitialTestExecutor One or more tests resulted in an error:
        Test runner crashed. Tried twice to restart it without any luck. Last time the error message was: Error: Child process [pid 20620] exited unexpectedly with exit code
 1 (without signal). Last part of stdout and stderr was:
        (node:20620) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'add' of undefined
        (node:20620) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch bloc
k, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
        (node:20620) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Nod
e.js process with a non-zero exit code.
        (node:20620) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'add' of undefined
        (node:20620) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch bloc
k, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
        C:\git\app_dir\node_modules\@stencil\core\dist\runtime\index.js:1351
            const elm = buildConditionals.BUILD.lazyLoad ? hostRef.$hostElement$ : ref;
                                                                   ^

        TypeError: Cannot read property '$hostElement$' of undefined
            at setValue (C:\git\app_dir\node_modules\@stencil\core\dist\runtime\index.js:1351:60)
            at MyAppTilesList.set [as tiles] (C:\git\app_dir\node_modules\@stencil\core\dist\runtime\index.js:1430:25)
            at Timeout._onTimeout (C:\git\app_dir\.stryker-tmp\sandbox6606588\src\components\my-app-tiles-list\my-app-tiles-list.tsx:119:24)
            at listOnTimeout (internal/timers.js:531:17)
            at processTimers (internal/timers.js:475:7)

Error: Child process [pid 20620] exited unexpectedly with exit code 1 (without signal). Last part of stdout and stderr was:
        (node:20620) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'add' of undefined
        (node:20620) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch bloc
k, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
        (node:20620) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Nod
e.js process with a non-zero exit code.
        (node:20620) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'add' of undefined
        (node:20620) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch bloc
k, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
        C:\git\app_dir\node_modules\@stencil\core\dist\runtime\index.js:1351
            const elm = buildConditionals.BUILD.lazyLoad ? hostRef.$hostElement$ : ref;
                                                                   ^

        TypeError: Cannot read property '$hostElement$' of undefined
            at setValue (C:\git\app_dir\node_modules\@stencil\core\dist\runtime\index.js:1351:60)
            at MyAppTilesList.set [as tiles] (C:\git\app_dir\node_modules\@stencil\core\dist\runtime\index.js:1430:25)
            at Timeout._onTimeout (C:\git\app_dir\.stryker-tmp\sandbox6606588\src\components\my-app-tiles-list\my-app-tiles-list.tsx:119:24)
            at listOnTimeout (internal/timers.js:531:17)
            at processTimers (internal/timers.js:475:7)

    at ChildProcessProxy.handleUnexpectedExit (C:\git\app_dir\node_modules\@stryker-mutator\core\src\child-proxy\ChildProcessProxy.js:33:37)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
21:03:52 (11320) ERROR StrykerCli an error occurred Error: Something went wrong in the initial test run
    at InitialTestExecutor.validateResult (C:\git\app_dir\node_modules\@stryker-mutator\core\src\process\InitialTestExecutor.js:86:15)
    at InitialTestExecutor.run (C:\git\app_dir\node_modules\@stryker-mutator\core\src\process\InitialTestExecutor.js:41:14)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Stryker.runMutationTest (C:\git\app_dir\node_modules\@stryker-mutator\core\src\Stryker.js:54:38)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! MyApp@0.0.66 stryker: `stryker run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the MyApp@0.0.66 stryker script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-12-30T19_03_52_322Z-debug.log
```
**Stryker config**
```js
module.exports = function(config) {
  config.set({
    mutator: "typescript",
    packageManager: "npm",
    reporters: ["html", "clear-text", "progress"],
    testRunner: "jest",
    transpilers: [],
    coverageAnalysis: "off",
    tsconfigFile: "tsconfig.json",
    mutate: ["**/src/**/*.ts",  "**/src/**/*.tsx", "!**/src/**/*.spec.*", "!cypress/**", "!node_modules"],
    logLevel: "all"
  });
};
```

**Test runner config**
Stencil.conf.js:
```js
  testing: {
    setupFiles: ['./jestPolyfill/EventTarget.js'],
    testRegex: "(.*\.(test|spec))\.(tsx|ts)$",
    testPathIgnorePatterns: ["\\.stencil", "\\.vscode", "\\dist", "\\node_modules", "\\www", "\\cypress", "\\.stryker-tmp"]
  }
```

**Stryker environment**

Using stryker 2.4.0 with no pluginx

```
+-- @stryker-mutator/html-reporter@2.4.0
| +-- @stryker-mutator/api@2.4.0 deduped
| +-- @stryker-mutator/util@2.4.0 deduped
+-- @stryker-mutator/jest-runner@2.4.0
| +-- @stryker-mutator/api@2.4.0 deduped
+-- @stryker-mutator/typescript@2.4.0
| +-- @stryker-mutator/api@2.4.0 deduped
| +-- @stryker-mutator/util@2.4.0 deduped
```

**Test runner environment**

```shell
stencil test src/* --spec    OR  jest src/*   (same)
```
**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             |  12.13.0
| npm              |  6.12.0
| Operating System | Windows 10

**Comment by aviadavi** [comment]
I used jest.useFakeTimers() in my tests and it worked.
