### ISSUE TITLE
PerTest option issue - SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1946]
**Summary**
```
08:29:51 (11148) ERROR InitialTestExecutor One or more tests resulted in an error:
        SyntaxError: Unexpected identifier
C:\Users\groszek\Desktop\BigMath\.stryker-tmp\sandbox7456346\src\basic.js:40
 */cov_2npd496e0a.s[208]++;exports.expm1=a=>{cov_2npd496e0a.f[12]++;cov_2npd496e0a.s[209]++;return exports.subtract(exports.exp(a),1n);};cov_2npd496e0a.s[210]++;exports.doubleFactorial=a=>{cov_2npd496e0a.f[13]++;cov_2npd496e0a.s[211]++;a=util_1.normalize(a);cov_2npd496e0a.s[212]++;if((cov_2npd496e0a.b[50][0]++,a.comma!==0)||(cov_2npd496e0a.b[50][1]++,a.sign)){cov_2npd496e0a.b[49][0]++;cov_2npd496e0a.s[213]++;throw new util_1.DomainError(util_1.stringify(a),'positive integers');}else{cov_2npd496e0a.b[49][1]++;}let n=(cov_2npd496e0a.s[214]++,a.number);cov_2npd496e0a.s[215]++;if(n<7n){cov_2npd496e0a.b[51][0]++;cov_2npd496e0a.s[216]++;return{comma:0,number:[1n,1n,2n,3n,8n,15n,48n][+`${n}`],sign:false};}else{cov_2npd496e0a.b[51][1]++;}cov_2npd496e0a.s[217]++;switch((n+1n)%4n){case0n:cov_2npd496e0a.b[52][0]++;const p=(cov_2npd496e0a.s[218]++,(n-1n)/2n);cov_2npd496e0a.s[219]++;n+=1n;let prod=(cov_2npd496e0a.s[220]++,1n);cov_2npd496e0a.s[2

SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:1055:16)
    at Module._compile (internal/modules/cjs/loader.js:1103:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\groszek\Desktop\BigMath\.stryker-tmp\sandbox7456346\src\BigMath.js:1:70956)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
08:29:51 (11148) ERROR StrykerCli an error occurred Error: Something went wrong in the initial test run
    at InitialTestExecutor.validateResult (C:\Users\groszek\Desktop\BigMath\node_modules\@stryker-mutator\core\src\process\InitialTestExecutor.js:86:15)
    at InitialTestExecutor.run (C:\Users\groszek\Desktop\BigMath\node_modules\@stryker-mutator\core\src\process\InitialTestExecutor.js:41:14)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Stryker.runMutationTest (C:\Users\groszek\Desktop\BigMath\node_modules\@stryker-mutator\core\src\Stryker.js:54:38) 
```

**Stryker config**

```js
module.exports = function(config) {
  config.set({
    mutator: 'typescript',
    packageManager: 'npm',
    reporters: ['html', 'clear-text', 'progress'],
    testRunner: 'mocha',
    transpilers: ['typescript'],
    testFramework: 'mocha',
    coverageAnalysis: 'perTest',
    tsconfigFile: 'tsconfig.json',
    mutate: ['src/**/*.ts']
  });
};
```

**Test runner config**

mocha + nyc + ts
```nycrc
{
  "extends": "@istanbuljs/nyc-config-typescript",
  "check-coverage": true,
  "lines": 100,
  "statements": 100,
  "functions": 100,
  "branches": 100,
  "compact": false,
  "reporter": [
    "html"
  ]
}
```

Again some problems with PerTest options.
changing coverageAnalysis to `off` fixes issue.
Honestly I don't know why this issue occurs, but I think too many `exports` / `lines` in 1 file can cause it (but I am not sure, since there is nothing really different from version to version [works for one, small changes - doesn't work])

Repo + build + PR:
https://github.com/kmdrGroch/BigMath
https://github.com/kmdrGroch/BigMath/pull/69
https://travis-ci.com/kmdrGroch/BigMath/jobs/271439516
(In this particular job there is no saying it's caused by stryker, but later on after some tweaks I got message like on top [tests and coverage run good]).
Changing `coverageAnalysis` works 

[stryker.log](https://github.com/stryker-mutator/stryker/files/4013865/stryker.log)

**Comment by simondel** [comment]
Hi @kmdrGroch is this still an issue?

**Comment by kmdrGroch** [comment]
@simondel yop
[stryker.log](https://github.com/stryker-mutator/stryker/files/4331521/stryker.log)

**Comment by kmdrGroch** [comment]
Any work/idea on this?
