### ISSUE TITLE
Stryker can't catch selenium: ChildProcessProxyWorker UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by maximelafarie** [stryker-mutator/stryker#1985]
I'm trying to run Stryker in an Angular 8 project. When I run `stryker run`, I've got the following error message:

```bash
14:49:00 (339) TRACE ChildProcessProxy 23 01 2020 14:49:00.773:INFO [karma-server]: Karma v4.2.0 server started at http://0.0.0.0:9876/

14:49:00 (339) TRACE ChildProcessProxy 23 01 2020 14:49:00.780:INFO [launcher]: Launching browsers selenium_chrome with concurrency unlimited

14:49:00 (339) TRACE ChildProcessProxy 23 01 2020 14:49:00.795:INFO [launcher]: Starting browser selenium for chrome

14:49:00 (339) TRACE ChildProcessProxy 23 01 2020 14:49:00.797:INFO [webdriverio]: Selenium browser started at http://selenium:4444/wd/hub

14:49:02 (350) DEBUG ChildProcessProxyWorker UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: getaddrinfo ENOTFOUND selenium selenium:4444
14:49:02 (339) TRACE ChildProcessProxy 23 01 2020 14:49:02.219:ERROR [karma-server]: UnhandledRejection
```

here's my stryker.config.js file content:

```javascript
module.exports = function (config) {
    config.set({
      mutate: [
        'src/**/*.ts',
        '!src/**/*.spec.ts',
        '!src/test.ts',
        '!src/environments/*.ts'
      ],
      files: [
        'src/**/*.ts',
        './karma.conf.ci.js'
      ],
      mutator: 'typescript',
      testRunner: 'karma',
      karma: {
        configFile: './karma.conf.ci.js',
        projectType: 'angular-cli'
      },
      logLevel: 'trace',
      reporters: ['progress', 'clear-text', 'html'],
      maxConcurrentTestRunners: 2, // Recommended to not use all cores when running stryker with angular.
      coverageAnalysis: 'off'
    });
  };
```

Do you guys have an idea about why Stryker can't wait for selenium browser?

**Comment by kmdrGroch** [comment]
hi, thanks for opening issue. Could you please provide whole Stryker.log? It would help a bit more :)

**Comment by maximelafarie** [comment]
Hi @kmdrGroch, sure, here it is:

```bash
> stryker run

10:23:57 (109) INFO ConfigReader Using stryker.conf.js in the current working directory.
10:24:01 (109) DEBUG BroadcastReporter Broadcasting to reporters ["progress","clear-text","html"]
10:24:02 (109) INFO InputFileResolver Found 356 of 547 file(s) to be mutated.
10:24:02 (109) DEBUG InputFileResolver All input files: [
  "all my TS sources files...",
  "/var/www/my-project/karma.conf.ci.js"
]
10:24:02 (109) DEBUG InputFileResolver Files to mutate: [
  "all my TS sources files"
]
10:24:02 (109) DEBUG TemporaryDirectory Using temp directory "/var/www/my-project/.stryker-tmp"
10:24:02 (109) DEBUG TestFrameworkOrchestrator The `coverageAnalysis` setting is "off", not hooking into the test framework to achieve performance benefits.
10:24:02 (109) INFO InitialTestExecutor Starting initial test run. This may take a while.
10:24:02 (109) DEBUG Sandbox Creating a sandbox for files in /var/www/my-project/.stryker-tmp/sandbox4747435
10:24:03 (109) DEBUG Sandbox Creating test runner 0
10:24:03 (109) DEBUG ChildProcessProxy Starting /var/www/my-project/node_modules/@stryker-mutator/core/src/test-runner/ChildProcessTestRunnerWorker.js in child process 120
10:24:28 (109) TRACE ChildProcessProxy Browserslist: caniuse-lite is outdated. Please run next command `npm update`
10:24:28 (109) TRACE ChildProcessProxy

10:24:04 (120) DEBUG ChildProcessProxyWorker Changing current working directory for this process to /var/www/my-project/.stryker-tmp/sandbox4747435
10:24:04 (120) DEBUG PluginLoader Loading @stryker-mutator/* from /var/www/my-project/node_modules/@stryker-mutator
10:24:05 (120) DEBUG PluginLoader Loading plugin "/var/www/my-project/node_modules/@stryker-mutator/html-reporter" (matched with expression @stryker-mutator/*)
10:24:05 (120) DEBUG PluginLoader Loading plugin "/var/www/my-project/node_modules/@stryker-mutator/jasmine-framework" (matched with expression @stryker-mutator/*)
10:24:05 (120) DEBUG PluginLoader Loading plugin "/var/www/my-project/node_modules/@stryker-mutator/karma-runner" (matched with expression @stryker-mutator/*)
10:24:05 (120) DEBUG PluginLoader Loading plugin "/var/www/my-project/node_modules/@stryker-mutator/typescript" (matched with expression @stryker-mutator/*)
10:24:05 (120) DEBUG PluginLoader Loading plugins /var/www/my-project/node_modules/@stryker-mutator/html-reporter
10:24:05 (120) DEBUG PluginLoader Loading plugins /var/www/my-project/node_modules/@stryker-mutator/jasmine-framework
10:24:05 (120) DEBUG PluginLoader Loading plugins /var/www/my-project/node_modules/@stryker-mutator/karma-runner
10:24:07 (120) DEBUG PluginLoader Loading plugins /var/www/my-project/node_modules/@stryker-mutator/typescript
10:24:07 (120) DEBUG PluginLoader Loading plugins /var/www/my-project/node_modules/@stryker-mutator/core/src/reporters/index.js
10:24:11 (120) DEBUG angularStarter.js Starting Angular tests: ng test --progress=false --karma-config=/var/www/my-project/node_modules/@stryker-mutator/karma-runner/src/starters/stryker-karma.conf.js
10:24:28 (120) DEBUG stryker-karma.conf.js Importing config from "/var/www/my-project/.stryker-tmp/sandbox4747435/karma.conf.ci.js"
10:24:56 (109) TRACE ChildProcessProxy 24 01 2020 10:24:56.530:INFO [karma-server]: Karma v4.2.0 server started at http://0.0.0.0:9876/

10:24:56 (109) TRACE ChildProcessProxy 24 01 2020 10:24:56.536:INFO [launcher]: Launching browsers selenium_chrome with concurrency unlimited

10:24:56 (109) TRACE ChildProcessProxy 24 01 2020 10:24:56.564:INFO [launcher]: Starting browser selenium for chrome

10:24:56 (109) TRACE ChildProcessProxy 24 01 2020 10:24:56.566:INFO [webdriverio]: Selenium browser started at http://selenium:4444/wd/hub

10:24:58 (120) DEBUG ChildProcessProxyWorker UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: getaddrinfo ENOTFOUND selenium selenium:4444
10:24:58 (109) TRACE ChildProcessProxy 24 01 2020 10:24:58.286:ERROR [karma-server]: UnhandledRejection

10:24:58 (109) ERROR StrykerCli an error occurred Error: Error: `ng test` command failed with exit code 1. Please run with logLevel 'trace' to see the angular-cli console output (actual command was ng test --progress=false --karma-config=/var/www/my-project/node_modules/@stryker-mutator/karma-runner/src/starters/stryker-karma.conf.js)
Error: `ng test` command failed with exit code 1. Please run with logLevel 'trace' to see the angular-cli console output (actual command was ng test --progress=false --karma-config=/var/www/my-project/node_modules/@stryker-mutator/karma-runner/src/starters/stryker-karma.conf.js)
    at cli.then (/var/www/my-project/node_modules/@stryker-mutator/karma-runner/src/starters/angularStarter.js:36:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at ChildProcess.worker.on (/var/www/my-project/node_modules/@stryker-mutator/core/src/child-proxy/ChildProcessProxy.js:133:68)
    at ChildProcess.emit (events.js:198:13)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 130
npm ERR! cadi@2.2.0 test:mutants: `stryker run`
npm ERR! Exit status 130
npm ERR!
npm ERR! Failed at the cadi@2.2.0 test:mutants script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-24T10_24_58_460Z-debug.log
root@58b306a63e60:/var/www/my-project#
```

**Comment by maximelafarie** [comment]
Additional note: I'm running it in a dockerized environment where my frontend app is running. The unit tests are running well and catch the selenium successfully. So I don't know why Stryker can't reach it or wait for it.

**Comment by kmdrGroch** [comment]
Please add trace log level

**Comment by maximelafarie** [comment]
@kmdrGroch I've already set it. You've the full log trace here (I just removed the entire source file name)

**Comment by maximelafarie** [comment]
I've already set it to `trace`. That's all I have. I only removed the entire list of source files names since it's big.

**Comment by simondel** [comment]
That's strange. The trace logging says Karma has started the browser but then it says it can't find the browser.

Would it be possible for you to reproduce the issue in a small repo? (I assume your project isn't open source)

**Comment by kmdrGroch** [comment]
@maximelafarie i meant this error:
Error: `ng test` command failed with exit code 1. Please run with logLevel 'trace' to see the angular-cli console output (actual command was ng test --progress=false --karma-config=/var/www/my-project/node_modules/@stryker-mutator/karma-runner/src/starters/stryker-karma.conf.js)

**Comment by simondel** [comment]
Hi! I'm closing this issue for now. If it still persists with Stryker version 4, please open a new issue. Thanks!
