### ISSUE TITLE
Error: Channel is closed when running mutation testing

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#218]
Sometimes Stryker gives a `channel is closed` error. @avassem85 got this stacktrace:

```bash
Mutation testing  [====================================              ] 72% (ETC 144.4s)[218 killed] [48 survived] [2438 no coverage] [0 timeout] [0 error][2017-01-11 10:32:25.812] [ERROR] IsolatedTestRunnerAdapter - /Users/avassem/Documents/Projects/InfoSupport/stryker/testprojects/Agora/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

TypeError: Cannot read property 'id' of undefined
    at persistence2.getById (/Users/avassem/Documents/Projects/InfoSupport/stryker/testprojects/Agora/.stryker-tmp/2346694/sandbox2630565/softwerkskammer/test/persistence/persistence_test_with_two_collections.js:30:26)
    at db.collection.find.toArray (/Users/avassem/Documents/Projects/InfoSupport/stryker/testprojects/Agora/.stryker-tmp/2346694/sandbox2630565/softwerkskammer/lib/persistence/persistence.js:74:30)
    at handleCallback (/Users/avassem/Documents/Projects/InfoSupport/stryker/testprojects/Agora/node_modules/mongodb/lib/utils.js:95:56)
    at /Users/avassem/Documents/Projects/InfoSupport/stryker/testprojects/Agora/node_modules/mongodb/lib/cursor.js:852:16
    at handleCallback (/Users/avassem/Documents/Projects/InfoSupport/stryker/testprojects/Agora/node_modules/mongodb-core/lib/cursor.js:171:5)
    at setCursorDeadAndNotified (/Users/avassem/Documents/Projects/InfoSupport/stryker/testprojects/Agora/node_modules/mongodb-core/lib/cursor.js:506:3)
    at nextFunction (/Users/avassem/Documents/Projects/InfoSupport/stryker/testprojects/Agora/node_modules/mongodb-core/lib/cursor.js:652:7)
    at Cursor.next [as _next] (/Users/avassem/Documents/Projects/InfoSupport/stryker/testprojects/Agora/node_modules/mongodb-core/lib/cursor.js:693:3)
    at fetchDocs (/Users/avassem/Documents/Projects/InfoSupport/stryker/testprojects/Agora/node_modules/mongodb/lib/cursor.js:848:10)
    at /Users/avassem/Documents/Projects/InfoSupport/stryker/testprojects/Agora/node_modules/mongodb/lib/cursor.js:871:7
    at handleCallback (/Users/avassem/Documents/Projects/InfoSupport/stryker/testprojects/Agora/node_modules/mongodb-core/lib/cursor.js:171:5)
    at nextFunction (/Users/avassem/Documents/Projects/InfoSupport/stryker/testprojects/Agora/node_modules/mongodb-core/lib/cursor.js:683:5)
    at /Users/avassem/Documents/Projects/InfoSupport/stryker/testprojects/Agora/node_modules/mongodb-core/lib/cursor.js:594:7
    at queryCallback (/Users/avassem/Documents/Projects/InfoSupport/stryker/testprojects/Agora/node_modules/mongodb-core/lib/cursor.js:253:5)
    at /Users/avassem/Documents/Projects/InfoSupport/stryker/testprojects/Agora/node_modules/mongodb-core/lib/connection/pool.js:455:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Mutation testing  [====================================              ] 72% (ETC 142.5s)[219 killed] [48 survived] [2438 no coverage] [0 timeout] [0 error]events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:548:16)
    at TestRunnerChildProcessAdapter.send (/Users/avassem/Documents/Projects/InfoSupport/stryker/testprojects/Agora/node_modules/stryker/src/isolated-runner/IsolatedTestRunnerAdapter.js:122:28)
    at TestRunnerChildProcessAdapter.sendDisposeCommand (/Users/avassem/Documents/Projects/InfoSupport/stryker/testprojects/Agora/node_modules/stryker/src/isolated-runner/IsolatedTestRunnerAdapter.js:135:14)
    at TestRunnerChildProcessAdapter.dispose (/Users/avassem/Documents/Projects/InfoSupport/stryker/testprojects/Agora/node_modules/stryker/src/isolated-runner/IsolatedTestRunnerAdapter.js:108:18)
    at TestRunnerChildProcessAdapter.handleTimeout (/Users/avassem/Documents/Projects/InfoSupport/stryker/testprojects/Agora/node_modules/stryker/src/isolated-runner/IsolatedTestRunnerAdapter.js:150:14)
    at Timeout.<anonymous> (/Users/avassem/Documents/Projects/InfoSupport/stryker/testprojects/Agora/node_modules/stryker/src/isolated-runner/IsolatedTestRunnerAdapter.js:145:19)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

Also reported by @zxxc in #214

**Comment by simondel** [comment]
This will be released as Stryker 0.6.0
