### ISSUE TITLE
Instrumentation seems to break jest's code transform: "Unsupported type ConditionalExpression"

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#2400]
(originally reported by @brodybits 🤘)

I tried with React (<https://github.com/facebook/react>). I was able to get through the initial test run with the following configuration in `stryker.conf.js` on a local build of Stryker 4.0.0-beta from GitHub after some trial-and-error:

```js
/**
 * @type {import('@stryker-mutator/api/core').StrykerOptions}
 */
module.exports = {
  mutator: 'javascript',
  packageManager: 'yarn',
  reporters: ['html', 'clear-text', 'progress'],
  testRunner: 'command',
  transpilers: [],
  coverageAnalysis: 'off',
  buildCommand: 'yarn',
  symlinkNodeModules: false,
  sandbox: {
    fileHeaders: {},
    stripComments: false
  },
};
```

(React test does seem to be extremely sensitive to the sandbox. The `sandbox` config does not seem to be supported by 4.0.0-beta.2 from npm.)

---

When I tried adding this mutate list:

```js
  mutate: [
    'packages/react/**/*.js',
    '!packages/react/node_modules/**/*.js',
    '!packages/react/__tests__/**/*.js',
  ],
```

then the initial test run failed. I got a huge number of errors from `npx stryker run --fileLogLevel trace --logLevel debug` starting with this:

```console
FAIL packages/react-dom/src/events/plugins/__tests__/EnterLeaveEventPlugin-test.js

  ● EnterLeaveEventPlugin › should set onMouseLeave relatedTarget properly in iframe

    /home/brodybits/react/.stryker-tmp/sandbox6232602/packages/react/src/ReactBaseClasses.js: Unsupported type ConditionalExpression

      20 |       return evalToString(ast.left) + evalToString(ast.right);
      21 |     default:
    > 22 |       throw new Error('Unsupported type ' + ast.type);
         |             ^
      23 |   }
      24 | }
      25 | 

      at evalToString (scripts/shared/evalToString.js:22:13)
      at PluginPass.CallExpression (scripts/error-codes/transform-error-messages.js:43:35)
      at newFn (node_modules/@babel/traverse/lib/visitors.js:179:21)
      at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:55:20)
      at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:42:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:90:31)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:112:16)
      at TraversalContext.visitSingle (node_modules/@babel/traverse/lib/context.js:84:19)
      at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:140:19)
      at Function.traverse.node (node_modules/@babel/traverse/lib/index.js:84:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:97:18)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:112:16)
      at TraversalContext.visitMultiple (node_modules/@babel/traverse/lib/context.js:79:17)
      at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:138:19)
      at Function.traverse.node (node_modules/@babel/traverse/lib/index.js:84:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:97:18)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:112:16)
      at TraversalContext.visitMultiple (node_modules/@babel/traverse/lib/context.js:79:17)
      at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:138:19)
      at Function.traverse.node (node_modules/@babel/traverse/lib/index.js:84:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:97:18)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:112:16)
      at TraversalContext.visitMultiple (node_modules/@babel/traverse/lib/context.js:79:17)
      at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:138:19)
      at Function.traverse.node (node_modules/@babel/traverse/lib/index.js:84:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:97:18)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:112:16)
      at TraversalContext.visitMultiple (node_modules/@babel/traverse/lib/context.js:79:17)
      at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:138:19)
      at Function.traverse.node (node_modules/@babel/traverse/lib/index.js:84:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:97:18)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:112:16)
      at TraversalContext.visitSingle (node_modules/@babel/traverse/lib/context.js:84:19)
      at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:140:19)
      at Function.traverse.node (node_modules/@babel/traverse/lib/index.js:84:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:97:18)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:112:16)
      at TraversalContext.visitSingle (node_modules/@babel/traverse/lib/context.js:84:19)
      at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:140:19)
      at Function.traverse.node (node_modules/@babel/traverse/lib/index.js:84:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:97:18)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:112:16)
      at TraversalContext.visitSingle (node_modules/@babel/traverse/lib/context.js:84:19)
      at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:140:19)
      at Function.traverse.node (node_modules/@babel/traverse/lib/index.js:84:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:97:18)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:112:16)
      at TraversalContext.visitMultiple (node_modules/@babel/traverse/lib/context.js:79:17)
      at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:138:19)
      at Function.traverse.node (node_modules/@babel/traverse/lib/index.js:84:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:97:18)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:112:16)
      at TraversalContext.visitSingle (node_modules/@babel/traverse/lib/context.js:84:19)
      at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:140:19)
      at Function.traverse.node (node_modules/@babel/traverse/lib/index.js:84:17)
      at traverse (node_modules/@babel/traverse/lib/index.js:66:12)
      at transformFile (node_modules/@babel/core/lib/transformation/index.js:107:29)
          at transformFile.next (<anonymous>)
      at run (node_modules/@babel/core/lib/transformation/index.js:35:12)
          at run.next (<anonymous>)
      at Function.transform (node_modules/@babel/core/lib/transform.js:27:41)
          at transform.next (<anonymous>)
      at evaluateSync (node_modules/gensync/index.js:244:28)
      at Function.sync (node_modules/gensync/index.js:84:14)
      at Object.transform (node_modules/@babel/core/lib/transform.js:36:54)
      at Object.process (scripts/jest/preprocessor.js:86:20)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:446:35)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:525:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:563:25)
      at Object.<anonymous> (packages/react/src/React.js:38:25)
      at Object.<anonymous> (packages/react/index.js:59:14)
      at Object.<anonymous> (packages/react-dom/src/events/plugins/__tests__/EnterLeaveEventPlugin-test.js:21:13)
```

**Comment by nicojs** [comment]
Ok, I did some investigation on this.

It appears that this line breaks after instrumentation:

```js
invariant(
    false,
    '%s(...): the first argument must be a React class instance. ' +
      'Instead received: %s.',
    methodName,
    received,
  );
```
(source: https://github.com/facebook/react/blob/d17086c7c813402a550d15a2f56dc43f1dbd1735/packages/react-dom/src/test-utils/ReactTestUtils.js#L110)

It is instrumented to be:

```js
__global_69fa48.__activeMutant__ === 47 ?
    ((__global_69fa48.__activeMutant__ === 53 ?
        typeof partialState !== 'object' :
        __global_69fa48.__activeMutant__ === 52 ? false
        : __global_69fa48.__activeMutant__ === 51 ? true
        : (__global_69fa48.__coverMutant__(51, 52, 53),
        typeof partialState === (__global_69fa48.__activeMutant__ === 54
            ? "" : (__global_69fa48.__coverMutant__(54), 'object'))))
            || (__global_69fa48.__activeMutant__ === 57 ?
                typeof partialState !== 'function' : __global_69fa48.__activeMutant__ === 56 ?
                false : __global_69fa48.__activeMutant__ === 55
                ? true : (__global_69fa48.__coverMutant__(55, 56, 57),
                typeof partialState === (__global_69fa48.__activeMutant__ === 58 ? ""
                : (__global_69fa48.__coverMutant__(58), 'function'))))) && partialState == null
                : __global_69fa48.__activeMutant__ === 46 ? false
                : __global_69fa48.__activeMutant__ === 45 ? true
                : (__global_69fa48.__coverMutant__(45, 46, 47), (__global_69fa48.__activeMutant__ === 50 ?
                    typeof partialState === (__global_69fa48.__activeMutant__ === 54 ? ""
                    : (__global_69fa48.__coverMutant__(54), 'object'))
                    && typeof partialState === (__global_69fa48.__activeMutant__ === 58 ? ""
                    : (__global_69fa48.__coverMutant__(58), 'function'))
                    : __global_69fa48.__activeMutant__ === 49 ? false
                    : __global_69fa48.__activeMutant__ === 48 ? true
                    : (__global_69fa48.__coverMutant__(48, 49, 50), (__global_69fa48.__activeMutant__ === 53 ? typeof partialState !== 'object'
                    : __global_69fa48.__activeMutant__ === 52 ? false : __global_69fa48.__activeMutant__ === 51 ? true
                    : (__global_69fa48.__coverMutant__(51, 52, 53), typeof partialState === (__global_69fa48.__activeMutant__ === 54 ? ""
                    : (__global_69fa48.__coverMutant__(54), 'object')))) || (__global_69fa48.__activeMutant__ === 57 ? typeof partialState !== 'function'
                    : __global_69fa48.__activeMutant__ === 56 ? false : __global_69fa48.__activeMutant__ === 55 ? true
                    : (__global_69fa48.__coverMutant__(55, 56, 57), typeof partialState === (__global_69fa48.__activeMutant__ === 58 ? ""
                    : (__global_69fa48.__coverMutant__(58), 'function')))))) || (__global_69fa48.__activeMutant__ === 61 ? partialState != null
                        : __global_69fa48.__activeMutant__ === 60 ? false : __global_69fa48.__activeMutant__ === 59 ? true
                        : (__global_69fa48.__coverMutant__(59, 60, 61), partialState == null))), __global_69fa48.__activeMutant__ === 62
                        ? 'setState(...): takes an object of state variables to update or a ' - 'function which returns an object of state variables.'
                        : (__global_69fa48.__coverMutant__(62), (__global_69fa48.__activeMutant__ === 63 ? ""
                        : (__global_69fa48.__coverMutant__(63), 'setState(...): takes an object of state variables to update or a '))
                        + (__global_69fa48.__activeMutant__ === 64 ? "" : (__global_69fa48.__coverMutant__(64), 'function which returns an object of state variables.')))
```

Agreed, it's a big mouth full. But a closer look led me to the conclusion that this is correctly instrumented. You can just run this code in node and it runs fine. However, when jest runs this code you get this error: `Unsupported type ConditionalExpression`.

A closer look into the `invariant` function gives me a clue:

```js
/**
 * Use invariant() to assert state which your program assumes to be true.
 * [...]
 *
 * The invariant message will be stripped in production, but the invariant
 * will remain to ensure logic does not differ in production.
 */
``` 

So it _strips_ the message on the production build. The only way I know of doing that safely is with a babel plugin. Looking closely to the error message and you see the culprit:

```
      at evalToString (scripts/shared/evalToString.js:23:13)
      at PluginPass.CallExpression (scripts/error-codes/transform-error-messages.js:43:35)
```

So there is a _custom transformer_ for _invariant_ calls that doesn't support our beautifully instrumented code 😢

I've fixed this by doing this:

```js
function evalToString(ast /* : Object */) /* : string */ {
  switch (ast.type) {
    case 'StringLiteral':
    case 'Literal': // ESLint
      return ast.value;
    case 'BinaryExpression': // `+`
      if (ast.operator !== '+') {
        throw new Error('Unsupported binary operator ' + ast.operator);
      }
      return evalToString(ast.left) + evalToString(ast.right);
    default:
      return ''; // Inserted this!
      // throw new Error('Unsupported type ' + ast.type);
  }
}
```

Now on to the next error:

```

Running tests for default (experimental)...
 FAIL  packages/react/src/__tests__/ReactTypeScriptClass-test.ts
  ● Test suite failed to run

    TypeError: /home/nicojs/react/stryker-tmp/sandbox3654894/packages/react/src/ReactChildren.js: Number of TemplateLiteral quasis should be exactly one more than the number of expressions.
    Expected 2 quasis but got 1

      49 |           // Outputs:
      50 |           //   `A ${adj} message that contains ${noun}`;
    > 51 |           const devMessage = t.templateLiteral(
         |                                ^
      52 |             errorMsgQuasis,
      53 |             errorMsgExpressions
      54 |           );

      at ../../node_modules/@babel/types/lib/definitions/core.js:1363:17
      at Object.validate (../../node_modules/@babel/types/lib/definitions/utils.js:229:7)
```

To be continued

**Comment by nicojs** [comment]
OK, I've investigated this some more. The `Number of TemplateLiteral quasis should be exactly one more than the number of expressions` error is directly related to the _invariant call_ fix I showed in my comment. This works:

```js
function evalToString(ast /* : Object */) /* : string */ {
  switch (ast.type) {
    case 'StringLiteral':
    case 'Literal': // ESLint
      return ast.value;
    case 'BinaryExpression': // `+`
      if (ast.operator !== '+') {
        throw new Error('Unsupported binary operator ' + ast.operator);
      }
      return evalToString(ast.left) + evalToString(ast.right);
    case 'SequenceExpression':
      return evalToString(ast.expressions[ast.expressions.length - 1]);
    case 'ConditionalExpression':
      return evalToString(ast.alternate);
    default:
      throw new Error('Unsupported type ' + ast.type);
  }
}
```

With all that out of the way, let's think of ways on how to support these scenarios. What is essentially happening here, is that React _isn't written in JavaScript_, instead, it is written in some language that looks like JavaScript, but treats `invariant` calls differently (FacebookScript?).

Probably it would make the most sense to simply ignore `invariant()` function calls all together when doing code instrumentation. This ties together with issue #2415. Let's discuss it there further.

**Comment by nicojs** [comment]
Closing this, as we figured out what was wrong. We will support this whenever we close #2415

**Comment by brodybits** [comment]
Thanks @nicojs. Applying your changes from <https://github.com/stryker-mutator/stryker/issues/2400#issuecomment-694954044> into `scripts/shared/evalToString.js` does to get me past the initial test run. Here is my configuration for future reference:

**`package.json`:** added `@stryker-mutator/core` version `^4.0.0-beta.8` to `devDependencies`

**`stryker.conf.js`** - with `mutate` & `buildCommand` added:

```js
/**
 * @type {import('@stryker-mutator/api/core').StrykerOptions}
 */
module.exports = {
  mutate: [
    'packages/react/**/*.js',
    '!packages/react/src/__tests__/**/*.js',
  ],
  packageManager: 'yarn',
  reporters: ['html', 'clear-text', 'progress'],
  testRunner: 'command',
  coverageAnalysis: 'off',
  buildCommand: 'yarn',
};
```

**`scripts/shared/evalToString.js`** - updated:

```js
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @flow
 */
'use strict';

function evalToString(ast /* : Object */) /* : string */ {
  switch (ast.type) {
    case 'StringLiteral':
    case 'Literal': // ESLint
      return ast.value;
    case 'BinaryExpression': // `+`
      if (ast.operator !== '+') {
        throw new Error('Unsupported binary operator ' + ast.operator);
      }
      return evalToString(ast.left) + evalToString(ast.right);
    // cases added by @nicojs:
    case 'SequenceExpression':
      return evalToString(ast.expressions[ast.expressions.length - 1]);
    case 'ConditionalExpression':
      return evalToString(ast.alternate);
    default:
      throw new Error('Unsupported type ' + ast.type);
  }
}

module.exports = evalToString;
```

I tried running Stryker with this command, to avoid memory & timeout issues:

```console
node --max-old-space-size=400000 ./node_modules/.bin/stryker run --timeoutMS 600000 --logLevel debug | tee stryker.out
```

But now I get timeouts during mutation testing, which seems very strange. Any pointers for further investigation would be much appreciated.
