### ISSUE TITLE
4.0.0.Beta: TypeError: Cannot read property 'static' of undefined

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#2473]
When running Stryker on Stryker's own `@stryker-mutator/mocha-runner`, there are test failures in the initial test run. 

For example:

```
  1) MochaAdapter
       collectFiles
         when mocha version < 6
           should log about mocha < 6 detection:
     TypeError: Cannot read property 'static' of undefined
      at g.__coverMutant__ (src/StrykerMochaReporter.js:14:38)
      at MochaAdapter.collectFiles (src/MochaAdapter.js:61:33)
      at Context.<anonymous> (test/unit/MochaAdapter.spec.js:48:21)
      at processImmediate (internal/timers.js:456:21)
      at process.callbackTrampoline (internal/async_hooks.js:120:14)
```

It seems that the properties on the `global` object are stripped during the test run.

The problem occurs in the instrumented code:

```js
  g.__coverMutant__ = g.__coverMutant__ || function () {
    var c = g.__mutantCoverage__.static;
                  //    ↪ this is `undefined`
    if (g.__currentTestId__) {
      c = g.__mutantCoverage__.perTest[g.__currentTestId__] = g.__mutantCoverage__.perTest[g.__currentTestId__] || {};
    }

    var a = arguments;

    for (var i = 0; i < a.length; i++) {
      c[a[i]] = (c[a[i]] || 0) + 1;
    }
  };
```

We should be able to declare `__mutantCoverage__` inside the closure and reuse it there. However, we might also want to investigate why this problem occurs (and why only with the `@stryker-mutator/mocha-runner` itself)

**Comment by nicojs** [comment]
Same for the jasmine runner:

```
20:18:45 (22937) ERROR DryRunExecutor One or more tests failed in the initial test run:
        JasmineTestRunner "before each" hook for "should configure jasmine on run"
                Could not inject [class JasmineTestRunner]. Cause: Cannot read property 'static' of undefined
20:18:45 (22937) ERROR Stryker There were failed tests in the initial test run.
```

**Comment by nicojs** [comment]
Do you think this afterEach logic might have something todo with it? 🙄

```ts
export const mochaHooks = {
  afterEach() {
    if (process.cwd() !== cwd) {
      process.chdir(cwd);
    }
    sinon.restore();
    testInjector.reset();
    StrykerMochaReporter.currentInstance = undefined;
    delete global.__currentTestId__;
    delete global.__mutantCoverage__;
    delete global.__activeMutant__;
  },
};
```
