### ISSUE TITLE
4.0.0.Beta: Must call super constructor in derived class before accessing 'this' or returning from derived constructor

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#2474]
When running Stryker on its own `@stryker-mutator/karma-runner`, we now get this error:

```  
ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor
ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor
    at new StrykerReporter (/home/nicojs/stryker/packages/karma-runner/.stryker-tmp/sandbox1223810/src/karma-plugins/StrykerReporter.ts:51:10)
    at Object.<anonymous> (/home/nicojs/stryker/packages/karma-runner/.stryker-tmp/sandbox1223810/src/karma-plugins/StrykerReporter.ts:68:39
```

**Cause**:

This:

```ts
export default class StrykerReporter extends EventEmitter implements karma.Reporter {
  public adapters: any[] = [];

  private constructor() {
    super();
  }
  // ...
}
```

Is mutated to:

```ts
export default class StrykerReporter extends EventEmitter implements karma.Reporter {
  public adapters: any[] = __global_69fa48.__activeMutant__ === 10 ? ["Stryker was here"] : (__global_69fa48.__coverMutant__(10), []);

  private constructor() {
    switch (__global_69fa48.__activeMutant__) {
      case 11:
        {}
        break;

      default:
        __global_69fa48.__coverMutant__(11);
        {
          super();
        }
        break;
    }
  }
 // ...
}
```

Which is then transpiled to:

```js
class StrykerReporter extends events_1.EventEmitter {
    constructor() {
        this.adapters = __global_69fa48.__activeMutant__ === 10 ? ["Stryker was here"] : (__global_69fa48.__coverMutant__(10), []);
        // ...
        switch (__global_69fa48.__activeMutant__) {
            case 11:
                { }
                break;
            default:
                __global_69fa48.__coverMutant__(11);
                {
                    super();
                }
                break;
        }
    }
   // ...
}
```

**Comment by dimitrilahaye** [comment]
Hi!
Even with the 6.2.0-beta.0 a class like that:

```javascript
export class BuyerRoute extends PbRoute {
  #traveler: string;
  
    constructor(input: BuyerRouteInput) {
        super(input);
        this.#traveler = input.traveler;
    }
}
```

Is still compiled by Stryker like that:

```javascript
export class BuyerRoute extends PbRoute {
    #traveler: string;

    constructor(input: BuyerRouteInput) {
        if (stryMutAct_9fa48("647")) { {}
        } else {
            stryCov_9fa48("647");
            super(input);
            this.#traveler = input.traveler;
        }
    }
}
```

Here my `stryker.conf.ts` file:

```javascript
// @ts-check
/** @type {import('@stryker-mutator/api/core').PartialStrykerOptions} */
const config = {
    _comment:
        "This config was generated using 'stryker init'. Please take a look at: https://stryker-mutator.io/docs/stryker-js/configuration/ for more information",
    packageManager: "yarn",
    reporters: ["html", "clear-text", "progress"],
    testRunner: "jest",
    coverageAnalysis: "perTest",
    checkers: ["typescript"],
    tsconfigFile: "tsconfig.json",
    transpilers: [
        "typescript", // Specify that your typescript code needs to be transpiled before tests can be run. Not needed if you're using ts-node Just-in-time compilation.
    ],
    jest: {
        projectType: "custom",
        configFile: "./jest.config.ts",
        enableFindRelatedTests: true,
    },
    disableTypeChecks: "{__tests__,src,lib}/**/*.{js,ts,jsx,tsx,html,vue}",
};
export default config;
```

**Comment by nicojs** [comment]
This seems like old config, because i see you've configured `transpilers`. This is no longer supported. Can you confirm the Stryker version for me? What does `npm ls @stryker-mutator/core` say?
