### ISSUE TITLE
SyntaxError: Unexpected character '#' on Typescript projects

### ISSUE THREAD

**Issue by cjimenezsaiz** [stryker-mutator/stryker#2585]
It looks like that there is a very similar issue (#1614) in the version 4.0.0 with the ts-parser:
```ts
export async function parse(text: string, fileName: string): Promise<TSAst> {
  const isTSX = fileName.endsWith('x');
  const ast = await parseAsync(text, {
    filename: fileName,
    parserOpts: {
      ranges: true,
    },
    configFile: false,
    babelrc: false,
    presets: [[require.resolve('@babel/preset-typescript'), { isTSX, allExtensions: true }]],
    plugins: [[require.resolve('@babel/plugin-proposal-decorators'), { legacy: true }]],
  });
```
The plugins for ts-parser are "hardcoded" and with a set of plugins that do not give support for private properties like `#hash`
```sh
Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-class-properties (https://git.io/vb4yQ) to the 'plugins' section to enable parsing.
    at Object._raise (D:\repository\Spider\NS-Netin-Logger-TypeScript\node_modules\@babel\parser\lib\index.js:766:17)
    at Object.raiseWithData (D:\repository\Spider\NS-Netin-Logger-TypeScript\node_modules\@babel\parser\lib\index.js:759:17)
    at Object.expectOnePlugin (D:\repository\Spider\NS-Netin-Logger-TypeScript\node_modules\@babel\parser\lib\index.js:8981:18)
    at Object.parseMaybePrivateName (D:\repository\Spider\NS-Netin-Logger-TypeScript\node_modules\@babel\parser\lib\index.js:10351:12)
    at Object.parsePropertyName (D:\repository\Spider\NS-Netin-Logger-TypeScript\node_modules\@babel\parser\lib\index.js:10854:155)
    at Object.parseClassElementName (D:\repository\Spider\NS-Netin-Logger-TypeScript\node_modules\@babel\parser\lib\index.js:12401:22)
    at Object.parseClassMemberWithIsStatic (D:\repository\Spider\NS-Netin-Logger-TypeScript\node_modules\@babel\parser\lib\index.js:12319:22)
    at Object.parseClassMemberWithIsStatic (D:\repository\Spider\NS-Netin-Logger-TypeScript\node_modules\@babel\parser\lib\index.js:6735:11)
    at Object.parseClassMember (D:\repository\Spider\NS-Netin-Logger-TypeScript\node_modules\@babel\parser\lib\index.js:12289:10)
    at Object.parseClassMember (D:\repository\Spider\NS-Netin-Logger-TypeScript\node_modules\@babel\parser\lib\index.js:6710:11) {
  loc: Position { line: 41, column: 2 },
  pos: 1635,
  missingPlugin: [ 'classPrivateProperties', 'classPrivateMethods' ],
  code: 'BABEL_PARSE_ERROR'
```

_Originally posted by @cjimenezsaiz in https://github.com/stryker-mutator/stryker/issues/1614#issuecomment-715891605_

**Comment by nicojs** [comment]
Thanks for opening this issue. It seems like a simple enough fix.

We want to keep the list of plugins hardcoded for now. Since TS supports #-privates, it was an oversight for us to not add those plugins.
