### ISSUE TITLE
Unexpected token on abstract Typescript function

### ISSUE THREAD

**Issue by J4Numbers** [stryker-mutator/stryker#2633]
**Summary**

On attempting to run Stryker over a Typescript test suite which is testing a set of Typescript classes, it fails while attempting to instrument an async abstract class which also contains defined functions inside.

To rephrase that slightly, on abstract classes which only contain async abstract methods, it is fine and instruments them to include 0 mutations as expected. On abstract classes which also contain functional code it fails with an:

```
16:45:48 (61668) DEBUG Instrumenter Instrumenting 89 source files with mutants
16:45:48 (61668) DEBUG Instrumenter Instrumented src/ts/authentication-management/index.ts (6 mutant(s))
16:45:48 (61668) DEBUG Instrumenter Instrumented src/ts/authentication-management/standard-authentication-manager.ts (0 mutant(s))
16:45:48 (61668) DEBUG Instrumenter Instrumented src/ts/authentication-management/username-password-authentication-manager.ts (12 mutant(s))
16:45:48 (61668) DEBUG Instrumenter Instrumented src/ts/authorisation/index.ts (6 mutant(s))
16:45:49 (61668) DEBUG Instrumenter Instrumented src/ts/authorisation/override-authorisation-checker.ts (12 mutant(s))
16:45:49 (61668) DEBUG Instrumenter Instrumented src/ts/authorisation/standard-authorisation-checker.ts (0 mutant(s))
16:45:49 (61668) DEBUG Instrumenter Instrumented src/ts/change-manager/change-manager.ts (65 mutant(s))
16:45:49 (61668) DEBUG Instrumenter Instrumented src/ts/change-manager/index.ts (6 mutant(s))
16:45:49 (61668) DEBUG Instrumenter Instrumented src/ts/config-transformer/config-transformer.ts (124 mutant(s))
16:45:49 (61668) DEBUG Instrumenter Instrumented src/ts/config-transformer/index.ts (6 mutant(s))
16:45:49 (61668) DEBUG Instrumenter Instrumented src/ts/config-uploader/aws-config-uploader.ts (25 mutant(s))
16:45:49 (61668) DEBUG Instrumenter Instrumented src/ts/config-uploader/index.ts (7 mutant(s))
16:45:49 (61668) DEBUG Stryker Not removing the temp dir because an error occurred
16:45:49 (61668) ERROR Stryker SyntaxError: /Users/[USER]/Documents/integration/git/routing-config-updater/src/ts/config-uploader/standard-config-uploader.ts: Unexpected token, expected "(" (48:17)

  46 |    * be using.
  47 |    */
> 48 |   async abstract getEncryptionKey(): Promise<Buffer>;
     |                  ^
  49 | 
  50 |   /**
  51 |    * Convert the various binary buffers that we have accumulated into a
```

I am not 100% sure whether this bug belongs to Stryker or to Babel; I am able to get around this issue by changing the abstract signature to:

```js
abstract getEncryptionKey(): Promise<Buffer>;
```

But a desired resolution would be to not care whether the `async` keyword is there.

Please let me know if there's anything else I can provide or if I need to copy this over to Babel.

Thanks.

**Repeatability instructions**

Given the two files:
```js
// Foo.ts
export default abstract class Foo {
  async abstract doThing(): Promise<number>;

  echoClass(): string {
    return 'Foo';
  }
}
```

and
```js
// Bar.ts
import Foo from './foo';

export default class Bar extends Foo {
  doThing(): number {
    return 42;
  }
}
```

Attempting to run a test suite which includes these two files should fail with the above error.

**Stryker config**

```js
/**
 * @type {import('@stryker-mutator/api/core').StrykerOptions}
 */
module.exports = {
  buildCommand: 'ts-node --transpile-only src/ts/**/*.ts',
  checkers: ['typescript'],
  commandRunner: {
    command: 'npm run test:ts',
  },
  coverageAnalysis: 'perTest',
  files: [
    'config/*.js',
    'public/**/*',
    'src/**/*.ts',
    'src/**/*.njk',
    'src/tsconfig.json',
    'test/.ts.mocharc.js',
    'test/**/*.js',
    'test/spec/ts/**/*.ts',
  ],
  htmlReporter: {
    baseDir: 'reports/ts/',
  },
  mochaOptions: {
    config: 'test/.ts.mocharc.js',
    require: ['ts-node/register', 'test/spec/helpers/setup.js'],
  },
  packageManager: 'npm',
  reporters: ['html', 'progress'],
  testRunner: 'mocha',
  tsconfigFile: 'src/tsconfig.json',
};
```

Note: Adding or removing the `buildCommand` and `mochaOptions.require` parts had no effect.

**Test runner config**

Mocha options:

```js
module.exports = {
  require: ['ts-node/register', 'test/spec/helpers/setup.js'],
  spec: 'test/spec/ts/**/*.ts',
  timeout: 5000,
  exit: true,
};
```

**Stryker environment**

```
├── @stryker-mutator/core@4.1.2
├── @stryker-mutator/mocha-runner@4.1.2
├── @stryker-mutator/typescript-checker@4.1.2
```

**Test runner environment*

```
├── chai@4.2.0
├── chai-as-promised@7.1.1
├── chai-http@4.3.0
├── clear-module@4.1.1
├── import-fresh@3.2.1
├── mocha@8.1.1
├── mock-require@3.0.3
├── nyc@15.1.0
├── sinon@9.0.3
├── sinon-chai@3.5.0
├── ts-mock-imports@1.3.0
├── ts-node@8.10.2
```

```shell
# npm run test:ts
TS_NODE_PROJECT=src/tsconfig.json nyc --nycrc-path nyc.ts.config.js --include src/**/*.ts mocha --config test/.ts.mocharc.js --check-leaks
```

```js
// .ts.mocharc.js
module.exports = {
  require: ['ts-node/register', 'test/spec/helpers/setup.js'],
  spec: 'test/spec/ts/**/*.ts',
  timeout: 5000,
  exit: true,
};
```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | `12.11.0`
| npm              | `6.11.3`
| Operating System | MacOS Mojave `10.14.6`

**Stryker Log**

```
17:16:51 (66036) DEBUG ConfigReader Loading config stryker.ts.conf.js
17:16:51 (66036) DEBUG BroadcastReporter Broadcasting to reporters ["html","progress"]
17:16:51 (66036) DEBUG ConfigReader Loaded config: {
  "buildCommand": "ts-node --transpile-only src/ts/**/*.ts",
  "checkers": [
    "typescript"
  ],
  "commandRunner": {
    "command": "npm run test:ts"
  },
  "coverageAnalysis": "perTest",
  "files": [
    "config/*.js",
    "public/**/*",
    "src/**/*.ts",
    "src/**/*.njk",
    "src/tsconfig.json",
    "test/.ts.mocharc.js",
    "test/**/*.js",
    "test/spec/ts/**/*.ts"
  ],
  "htmlReporter": {
    "baseDir": "reports/ts/"
  },
  "mochaOptions": {
    "config": "test/.ts.mocharc.js",
    "require": [
      "ts-node/register",
      "test/spec/helpers/setup.js"
    ]
  },
  "packageManager": "npm",
  "reporters": [
    "html",
    "progress"
  ],
  "testRunner": "mocha",
  "tsconfigFile": "src/tsconfig.json",
  "allowConsoleColors": true,
  "maxTestRunnerReuse": 0,
  "clearTextReporter": {
    "allowColor": true,
    "logTests": true,
    "maxTestsToLog": 3
  },
  "dashboard": {
    "baseUrl": "https://dashboard.stryker-mutator.io/api/reports",
    "reportType": "full"
  },
  "eventReporter": {
    "baseDir": "reports/mutation/events"
  },
  "fileLogLevel": "trace",
  "logLevel": "debug",
  "maxConcurrentTestRunners": 9007199254740991,
  "mutate": [
    "{src,lib}/**/!(*.+(s|S)pec|*.+(t|T)est).+(cjs|mjs|js|ts|jsx|tsx|html|vue)",
    "!{src,lib}/**/__tests__/**/*.+(cjs|mjs|js|ts|jsx|tsx|html|vue)"
  ],
  "mutator": {
    "plugins": null,
    "excludedMutations": []
  },
  "plugins": [
    "@stryker-mutator/*"
  ],
  "appendPlugins": [],
  "disableTypeChecks": "{test,src,lib}/**/*.{js,ts,jsx,tsx,html,vue}",
  "symlinkNodeModules": true,
  "tempDirName": ".stryker-tmp",
  "cleanTempDir": true,
  "thresholds": {
    "high": 80,
    "low": 60,
    "break": null
  },
  "timeoutFactor": 1.5,
  "timeoutMS": 5000,
  "warnings": true,
  "configFile": "stryker.ts.conf.js"
}
17:16:51 (66036) DEBUG PluginLoader Loading @stryker-mutator/* from /Users/[USER]/Documents/integration/git/routing-config-updater/node_modules/@stryker-mutator
17:16:51 (66036) DEBUG PluginLoader Loading plugin "/Users/[USER]/Documents/integration/git/routing-config-updater/node_modules/@stryker-mutator/instrumenter" (matched with expression @stryker-mutator/*)
17:16:51 (66036) DEBUG PluginLoader Loading plugin "/Users/[USER]/Documents/integration/git/routing-config-updater/node_modules/@stryker-mutator/mocha-runner" (matched with expression @stryker-mutator/*)
17:16:51 (66036) DEBUG PluginLoader Loading plugin "/Users/[USER]/Documents/integration/git/routing-config-updater/node_modules/@stryker-mutator/typescript-checker" (matched with expression @stryker-mutator/*)
17:16:51 (66036) DEBUG PluginLoader Loading plugins /Users/[USER]/Documents/integration/git/routing-config-updater/node_modules/@stryker-mutator/instrumenter
17:16:51 (66036) DEBUG PluginLoader Loading plugins /Users/[USER]/Documents/integration/git/routing-config-updater/node_modules/@stryker-mutator/mocha-runner
17:16:51 (66036) DEBUG PluginLoader Loading plugins /Users/[USER]/Documents/integration/git/routing-config-updater/node_modules/@stryker-mutator/typescript-checker
17:16:51 (66036) DEBUG PluginLoader Loading plugins /Users/[USER]/Documents/integration/git/routing-config-updater/node_modules/@stryker-mutator/core/src/reporters/index.js
17:16:51 (66036) DEBUG buildSchemaWithPluginContributions Contributing 1 schemas from plugins to options validation.
17:16:51 (66036) INFO InputFileResolver Found 89 of 218 file(s) to be mutated.
17:16:51 (66036) DEBUG InputFileResolver All input files: [
  "Very long list of all files"
]
17:16:51 (66036) DEBUG InputFileResolver Files to mutate: [
  "/Users/[USER]/Documents/integration/git/routing-config-updater/src/ts/authentication-management/index.ts",
  "/Users/[USER]/Documents/integration/git/routing-config-updater/src/ts/authentication-management/standard-authentication-manager.ts",
  "/Users/[USER]/Documents/integration/git/routing-config-updater/src/ts/authentication-management/username-password-authentication-manager.ts",
  "/Users/[USER]/Documents/integration/git/routing-config-updater/src/ts/authorisation/index.ts",
  "/Users/[USER]/Documents/integration/git/routing-config-updater/src/ts/authorisation/override-authorisation-checker.ts",
  "/Users/[USER]/Documents/integration/git/routing-config-updater/src/ts/authorisation/standard-authorisation-checker.ts",
  "/Users/[USER]/Documents/integration/git/routing-config-updater/src/ts/change-manager/change-manager.ts",
  "/Users/[USER]/Documents/integration/git/routing-config-updater/src/ts/change-manager/index.ts",
  "/Users/[USER]/Documents/integration/git/routing-config-updater/src/ts/config-transformer/config-transformer.ts",
  "/Users/[USER]/Documents/integration/git/routing-config-updater/src/ts/config-transformer/index.ts",
  "/Users/[USER]/Documents/integration/git/routing-config-updater/src/ts/config-uploader/aws-config-uploader.ts",
  "/Users/[USER]/Documents/integration/git/routing-config-updater/src/ts/config-uploader/index.ts",
  "/Users/[USER]/Documents/integration/git/routing-config-updater/src/ts/config-uploader/standard-config-uploader.ts",
  "/Users/[USER]/Documents/integration/git/routing-config-updater/src/ts/data-management/change-management/change-ticket/index.ts",
  "/Users/[USER]/Documents/integration/git/routing-config-updater/src/ts/data-management/change-management/change-ticket/mongo-change-ticket-data-management.ts",
  "/Users/[USER]/Documents/integration/git/routing-config-updater/src/ts/data-management/change-management/change-ticket/standard-change-ticket-data-management.ts",
  "/Users/[USER]/Documents/integration/git/routing-config-updater/src/ts/data-management/change-management/change-ticket/test-change-ticket-data-management.ts",
  "Slightly shorter list of all files"
]
17:16:51 (66036) DEBUG TemporaryDirectory Using temp directory "/Users/[USER]/Documents/integration/git/routing-config-updater/.stryker-tmp"
17:16:51 (66036) DEBUG Instrumenter Instrumenting 89 source files with mutants
17:16:52 (66036) DEBUG Instrumenter Instrumented src/ts/authentication-management/index.ts (6 mutant(s))
17:16:52 (66036) DEBUG Instrumenter Instrumented src/ts/authentication-management/standard-authentication-manager.ts (0 mutant(s))
17:16:52 (66036) DEBUG Instrumenter Instrumented src/ts/authentication-management/username-password-authentication-manager.ts (12 mutant(s))
17:16:52 (66036) DEBUG Instrumenter Instrumented src/ts/authorisation/index.ts (6 mutant(s))
17:16:52 (66036) DEBUG Instrumenter Instrumented src/ts/authorisation/override-authorisation-checker.ts (12 mutant(s))
17:16:52 (66036) DEBUG Instrumenter Instrumented src/ts/authorisation/standard-authorisation-checker.ts (0 mutant(s))
17:16:52 (66036) DEBUG Instrumenter Instrumented src/ts/change-manager/change-manager.ts (65 mutant(s))
17:16:52 (66036) DEBUG Instrumenter Instrumented src/ts/change-manager/index.ts (6 mutant(s))
17:16:52 (66036) DEBUG Instrumenter Instrumented src/ts/config-transformer/config-transformer.ts (124 mutant(s))
17:16:52 (66036) DEBUG Instrumenter Instrumented src/ts/config-transformer/index.ts (6 mutant(s))
17:16:52 (66036) DEBUG Instrumenter Instrumented src/ts/config-uploader/aws-config-uploader.ts (25 mutant(s))
17:16:52 (66036) DEBUG Instrumenter Instrumented src/ts/config-uploader/index.ts (7 mutant(s))
17:16:52 (66036) DEBUG Stryker Not removing the temp dir because an error occurred
17:16:52 (66036) ERROR Stryker SyntaxError: /Users/[USER]/Documents/integration/git/routing-config-updater/src/ts/config-uploader/standard-config-uploader.ts: Unexpected token, expected "(" (48:17)

  46 |    * be using.
  47 |    */
> 48 |   async abstract getEncryptionKey(): Promise<Buffer>;
     |                  ^
  49 | 
  50 |   /**
  51 |    * Convert the various binary buffers that we have accumulated into a
    at Object._raise (/Users/[USER]/Documents/integration/git/routing-config-updater/node_modules/@stryker-mutator/instrumenter/node_modules/@babel/parser/lib/index.js:748:17)
    at Object.raiseWithData (/Users/[USER]/Documents/integration/git/routing-config-updater/node_modules/@stryker-mutator/instrumenter/node_modules/@babel/parser/lib/index.js:741:17)
    at Object.raise (/Users/[USER]/Documents/integration/git/routing-config-updater/node_modules/@stryker-mutator/instrumenter/node_modules/@babel/parser/lib/index.js:735:17)
    at Object.unexpected (/Users/[USER]/Documents/integration/git/routing-config-updater/node_modules/@stryker-mutator/instrumenter/node_modules/@babel/parser/lib/index.js:9097:16)
    at Object.expect (/Users/[USER]/Documents/integration/git/routing-config-updater/node_modules/@stryker-mutator/instrumenter/node_modules/@babel/parser/lib/index.js:9083:28)
    at Object.parseFunctionParams (/Users/[USER]/Documents/integration/git/routing-config-updater/node_modules/@stryker-mutator/instrumenter/node_modules/@babel/parser/lib/index.js:12386:10)
    at Object.parseFunctionParams (/Users/[USER]/Documents/integration/git/routing-config-updater/node_modules/@stryker-mutator/instrumenter/node_modules/@babel/parser/lib/index.js:7018:11)
    at Object.parseMethod (/Users/[USER]/Documents/integration/git/routing-config-updater/node_modules/@stryker-mutator/instrumenter/node_modules/@babel/parser/lib/index.js:11127:10)
    at Object.pushClassMethod (/Users/[USER]/Documents/integration/git/routing-config-updater/node_modules/@stryker-mutator/instrumenter/node_modules/@babel/parser/lib/index.js:12678:30)
    at Object.pushClassMethod (/Users/[USER]/Documents/integration/git/routing-config-updater/node_modules/@stryker-mutator/instrumenter/node_modules/@babel/parser/lib/index.js:6988:11) {
  loc: Position { line: 48, column: 17 },
  pos: 1414,
  code: 'BABEL_PARSE_ERROR'
}
```

**Comment by J4Numbers** [comment]
I wouldn't mind _as_ much if it was one or the other, but given the file:

```js
// src/ts/authentication-management/standard_authentication_manager.ts
import { UserSession } from '../objects/user-session';
import { AuthenticationDetails } from '../objects/authentication-details';

export default abstract class StandardAuthenticationManager {
  abstract async login(authenticationDetails: AuthenticationDetails): Promise<UserSession>;
}
```

It interprets it fine (as seen in the larger ticket above).

**Comment by kmdrGroch** [comment]
I do believe `abstract async` feature has been removed in typescript 4.1 :) https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#abstract-members-cant-be-marked-async

**Comment by J4Numbers** [comment]
Fair enough, I can remove them to solve my issues. Not sure if there's anything the repo can do to point the user to a mismatch between the Stryker TS linter (which in this case seems to be running at `> 4.1.x`) and the Typescript engine that a codebase is currently working off of (i.e. mine is still on `3.9.7`) as it seems like it might cause some confusion/breaking changes for codebases reliant on newly-removed features.

**Comment by kmdrGroch** [comment]
I mean, I am not sure if that is the case... I am just saying that typescript 4.1 removes this, I am not sure why babel threw error there :/

**Comment by kmdrGroch** [comment]
Ok, I have checked it.
This syntax doesn't work in Babel, see: [this](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAE2AMwIYFcA29UCMDOMUqAxvCZqvvnAGIQRwDeAUHHFQJ4B2JHBRUvAQQAKgAsAltwDmACgCUALjgAFKBAC2k_MAA83dJtzAoAPgDcLNnGAlxEAMKVqilYSjSZzG-yjAYdChuOAByeghQq3YAXxYYoA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ces2015%2Ctypescript&prettier=false&targets=&version=7.12.9&externalPlugins=)

**Comment by J4Numbers** [comment]
Fair enough. Thanks for looking into it.
