### ISSUE TITLE
TypeError: Cannot read property 'buildError' on undefined

### ISSUE THREAD

**Issue by kwisatz** [stryker-mutator/stryker#2695]
**Summary**

Stryker triggers a bug with babel/core referenced in https://github.com/babel/babel/issues/8617. I do not have enough insight into the AST to understand what causes this, but it seems to be related to how `stryker` makes use of `babel-traverse`.

```shell
16:43:03 (24042) ERROR Stryker TypeError: Cannot read property 'buildError' of undefined
    at NodePath.buildCodeFrameError (/home/kwisatz/1024/projects/PROJECT_NAME/node_modules/@babel/traverse/lib/path/index.js:138:21)
    at Object.placeMutants (/home/kwisatz/1024/projects/PROJECT_NAME/node_modules/@stryker-mutator/instrumenter/dist/src/mutant-placers/index.js:31:28)
    at exit (/home/kwisatz/1024/projects/PROJECT_NAME/node_modules/@stryker-mutator/instrumenter/dist/src/transformers/babel-transformer.js:28:34)
    at NodePath._call (/home/kwisatz/1024/projects/PROJECT_NAME/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/home/kwisatz/1024/projects/PROJECT_NAME/node_modules/@babel/traverse/lib/path/context.js:38:14)
    at NodePath.visit (/home/kwisatz/1024/projects/PROJECT_NAME/node_modules/@babel/traverse/lib/path/context.js:101:8)
    at TraversalContext.visitQueue (/home/kwisatz/1024/projects/PROJECT_NAME/node_modules/@babel/traverse/lib/context.js:115:16)
    at TraversalContext.visitSingle (/home/kwisatz/1024/projects/PROJECT_NAME/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/home/kwisatz/1024/projects/PROJECT_NAME/node_modules/@babel/traverse/lib/context.js:143:19)
    at Function.traverse.node (/home/kwisatz/1024/projects/PROJECT_NAME/node_modules/@babel/traverse/lib/index.js:82:17)
```

**Stryker config**

```javascript
{
function filesToMutate() {
  switch (process.env.SCENARIO) {
    default:
    case 'server':
      return [
        "modules/server/src/**/*.js",
        "modules/server/src/**/*.ts",
        "modules/shared/src/**/*.ts",
      ];
      break;
    case 'web':
      return [
        "modules/web/src/**/*.ts",
        "modules/web/src/**/*.vue",
      ];
      break;
  }
}

// Please see the handbook for more information: https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/guides/vuejs.md#vuejs
module.exports = {
  concurrency: 8,
  mutate: filesToMutate(),
  testRunner: "jest",
  jest: {
    config: require('./jest.conf.js'),
    enableFindRelatedTests: true,
  },
  tsconfigFile: "tsconfig.json",
  reporters: ["progress", "clear-text", "html"],
  htmlReporter: {
    baseDir: `reports/mutation/${process.env.SCENARIO}`
  },
  disableTypeChecks: "{modules,test,src,lib}/**/*.{js,ts,jsx,tsx,html,vue}",
  coverageAnalysis: "off"
};
}
```

**Test runner config**

```javascript
const { globals } = require('./configGlobals');

const scenarioDependendIgnorePatterns = function () {
  switch (process.env.SCENARIO) {
    case 'unit':
      return [
        '/modules/server/test/e2e/',
        '/modules/server/test/io/',
        '/modules/server/test/integrity/',
        '/modules/web/test/e2e',
      ];
    break;
     […]
    case 'server':
      return [
        '/modules/server/test/e2e',
        '/modules/server/test/io',
        '/modules/server/test/integrity',
        '/modules/shared/test/',
        '/modules/web/test/',
      ];
      break;
    case 'web':
      return [
        '/modules/server/test/',
        '/modules/shared/test/',
        '/modules/web/test/e2e',
      ];
      break;
  default:
    return [];
  break;
  }
}

// We don't need `moduleNameMapper` (see https://kulshekhar.github.io/ts-jest/user/config/)
// since jest-webpack-resolver takes care of that for us.
module.exports = {
  cacheDirectory:          '/var/tmp/jest',
  testEnvironment:         'node',
  testURL:                 'http://localhost/',
  resolver:                'jest-webpack-resolver',
  moduleFileExtensions:    ['js', 'json', 'vue', 'ts'],
  setupFiles:              ['<rootDir>/modules/web/test/unit/setup-jest.ts'],

  transformIgnorePatterns: [
    'node_modules/(?!(vue)/)',
  ],

  testMatch: [
    "**/test/!(fixtures|files|assets)/!(setup-jest)*.[jt]s?(x)",
    "**/*?(.-)+(spec|test)?(s).[jt]s?(x)"
  ],

  testPathIgnorePatterns: [
    '/dist/',
    '/node_modules/',
    '/serve/',
    ...scenarioDependendIgnorePatterns(),
  ],

  transform: {
    '\\.ts$':  'ts-jest',
    '\\.js$':  'ts-jest',
    '\\.vue$': 'vue-jest'
  },

  globals: {
    ...globals,
  },
};
```

**Stryker environment**

```
├─┬ @stryker-mutator/core@4.3.1
│ ├─┬ @stryker-mutator/api@4.3.1
│ ├─┬ @stryker-mutator/instrumenter@4.3.1
│ │ ├── @stryker-mutator/api@4.3.1 deduped
│ │ ├── @stryker-mutator/util@4.3.1 deduped
│ ├─┬ @stryker-mutator/util@4.3.1
├─┬ @stryker-mutator/jest-runner@4.3.1
│ ├── @stryker-mutator/api@4.3.1 deduped
│ ├── @stryker-mutator/util@4.3.1 deduped
```

```
├── @types/jest@23.3.14
─┬ jest@23.6.0
│ └─┬ jest-cli@23.6.0
│   ├─┬ jest-changed-files@23.4.2
│   ├─┬ jest-config@23.6.0
│   │ ├─┬ babel-jest@23.6.0
│   │ │ └─┬ babel-preset-jest@23.2.0
│   │ │   ├── babel-plugin-jest-hoist@23.2.0
│   │ ├── jest-environment-jsdom@23.4.0 deduped
│   │ ├─┬ jest-environment-node@23.4.0
│   │ │ ├── jest-mock@23.2.0 deduped
│   │ │ └── jest-util@23.4.0 deduped
│   │ ├── jest-get-type@22.4.3 deduped
│   │ ├─┬ jest-jasmine2@23.6.0
│   │ │ │ ├── jest-diff@23.6.0 deduped
│   │ │ │ ├── jest-get-type@22.4.3 deduped
│   │ │ │ ├── jest-matcher-utils@23.6.0 deduped
│   │ │ │ ├── jest-message-util@23.4.0 deduped
│   │ │ │ └── jest-regex-util@23.3.0 deduped
│   │ │ ├── jest-diff@23.6.0 deduped
│   │ │ ├─┬ jest-each@23.6.0
│   │ │ ├── jest-matcher-utils@23.6.0 deduped
│   │ │ ├── jest-message-util@23.4.0 deduped
│   │ │ ├── jest-snapshot@23.6.0 deduped
│   │ │ ├── jest-util@23.4.0 deduped
│   │ ├── jest-regex-util@23.3.0 deduped
│   │ ├─┬ jest-resolve@23.6.0
│   │ ├── jest-util@23.4.0 deduped
│   │ ├── jest-validate@23.6.0 deduped
│   ├─┬ jest-environment-jsdom@23.4.0
│   │ ├── jest-mock@23.2.0
│   │ ├── jest-util@23.4.0 deduped
│   ├── jest-get-type@22.4.3
│   ├─┬ jest-haste-map@23.6.0
│   │ ├─┬ jest-docblock@23.2.0
│   │ ├── jest-serializer@23.0.1
│   │ ├─┬ jest-worker@23.2.0
│   ├─┬ jest-message-util@23.4.0
│   ├── jest-regex-util@23.3.0
│   ├─┬ jest-resolve-dependencies@23.6.0
│   │ ├── jest-regex-util@23.3.0 deduped
│   │ └── jest-snapshot@23.6.0 deduped
│   ├─┬ jest-runner@23.6.0
│   │ ├── jest-config@23.6.0 deduped
│   │ ├── jest-docblock@23.2.0 deduped
│   │ ├── jest-haste-map@23.6.0 deduped
│   │ ├── jest-jasmine2@23.6.0 deduped
│   │ ├─┬ jest-leak-detector@23.6.0
│   │ ├── jest-message-util@23.4.0 deduped
│   │ ├── jest-runtime@23.6.0 deduped
│   │ ├── jest-util@23.4.0 deduped
│   │ ├─┬ jest-worker@23.2.0
│   ├─┬ jest-runtime@23.6.0
│   │ ├── jest-config@23.6.0 deduped
│   │ ├── jest-haste-map@23.6.0 deduped
│   │ ├── jest-message-util@23.4.0 deduped
│   │ ├── jest-regex-util@23.3.0 deduped
│   │ ├── jest-resolve@23.6.0 deduped
│   │ ├── jest-snapshot@23.6.0 deduped
│   │ ├── jest-util@23.4.0 deduped
│   │ ├── jest-validate@23.6.0 deduped
│   ├─┬ jest-snapshot@23.6.0
│   │ ├─┬ jest-diff@23.6.0
│   │ │ ├── jest-get-type@22.4.3 deduped
│   │ ├─┬ jest-matcher-utils@23.6.0
│   │ │ ├── jest-get-type@22.4.3 deduped
│   │ ├── jest-message-util@23.4.0 deduped
│   │ ├── jest-resolve@23.6.0 deduped
│   ├─┬ jest-util@23.4.0
│   │ ├── jest-message-util@23.4.0 deduped
│   ├─┬ jest-validate@23.6.0
│   │ ├── jest-get-type@22.4.3 deduped
│   ├─┬ jest-watcher@23.4.0
│   ├─┬ jest-worker@23.2.0
├─┬ jest-webpack-resolver@0.3.0
│ ├─┬ jest-worker@26.3.0
├─┬ ts-jest@23.10.5
├─┬ vue-jest@3.0.7
```

**Test runner environment**

```shell
$ SCENARIO=web ./icu-npx stryker-cli run --fileLogLevel trace --logLevel debug
```

```json
{
  "compilerOptions": {
    "allowJs":                      true,
    "resolveJsonModule":            true,
    "emitDecoratorMetadata":        true,
    "experimentalDecorators":       true,
    "allowSyntheticDefaultImports": true,
    "baseUrl":                      "./",
    "strict":                       true,
    "moduleResolution":             "node",
    "target":                       "es2018",
    "module":                       "esnext",
    "outDir":                       "/dev/null",
    "lib":                          ["es7", "esnext", "es6", "dom", "dom.iterable"],

    "paths": {
      "@/*":            ["modules/web/src/*"],
      "tokei-server/*": ["modules/server/*"],
      "tokei-shared/*": ["modules/shared/*"],
      "tokei-db/*":     ["db/*"]
    }
  },

  "exclude": [
    "db/migrations/archive/*",
    "dist/*",
    "serve/*"
  ],

  "include": [
    "db/migrations/**/*.ts",
    "db/seeds/**/*.ts",
    "modules/server/src/**/*.ts",
    "modules/server/src/**/*.js",
    "modules/shared/src/**/*.ts",
    "modules/shared/src/**/*.js",
    "modules/web/src/**/*.vue",
    "modules/web/src/**/*.js",
    "modules/web/src/**/*.ts",
    "**/test/**/*.js",
    "**/test/**/*.ts",
    "node_modules/vue/dist/vue.esm.js",
    "vue-i18n/types/index.d.ts",
    "bin/**/*.ts",
    "bin/**/*.js",
    "vue-shim.d.ts"
  ]
}

```

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | 10.23.1
| npm              | 6.14.10
| Operating System | Debian 10.7

**Add stryker.log**

[stryker.log](https://github.com/stryker-mutator/stryker/files/5821495/stryker.log)

**Comment by nicojs** [comment]
This is a weird bug. We're using this workaround to make sure `this.hub.buildError` is defined within babel: https://github.com/babel/babel/issues/11889

Could you please try to find out which file gives the error? The easiest way is to open `node_modules/@stryker-mutator/instrumenter/dist/src/mutant-placers/index.js` and change these lines:

```diff
const location = `${path_1.default.relative(process.cwd(), fileName)}:${(_a = node.node.loc) === null || _a === void 0 ? void 0 : _a.start.line}:${(_b = node.node.loc) === null || _b === void 0 ? void 0 : _b.start.column}`;
const message = `${placer.name} could not place mutants with type(s): "${mutants.map((mutant) => mutant.mutatorName).join(', ')}"`;
-throw node.buildCodeFrameError(`${location} ${message}. Either remove this file from the list of files to be mutated, or ignore the mutators. Please report this issue at https://github.com/stryker-mutator/stryker/issues/new?assignees=&labels=%F0%9F%90%9B+Bug&template=bug_report.md&title=${encodeURIComponent(message)}.`);
+throw Error(`${location} ${message}. Either remove this file from the list of files to be mutated, or ignore the mutators. Please report this issue at https://github.com/stryker-mutator/stryker/issues/new?assignees=&labels=%F0%9F%90%9B+Bug&template=bug_report.md&title=${encodeURIComponent(message)}.`);
```

**Comment by kwisatz** [comment]
Thanks for your reply, @nicojs 

Here's the output of running stryker with the line changed as suggested (default log levels):

```bash
18:04:29 (10041) ERROR Stryker Error: modules/web/src/document-categories/document-category-form.vue:372:6 expressionMutantPlacer could not place mutants with type(s): "StringLiteral". Either remove this file from the list of files to be mutated, or ignore the mutators. Please report this issue at https://github.com/stryker-mutator/stryker/issues/new?assignees=&labels=%F0%9F%90%9B+Bug&template=bug_report.md&title=expressionMutantPlacer%20could%20not%20place%20mutants%20with%20type(s)%3A%20%22StringLiteral%22.
    at Object.placeMutants (/home/kwisatz/1024/projects/PROJECT_NAME/node_modules/@stryker-mutator/instrumenter/dist/src/mutant-placers/index.js:32:23)
```

Well… there not being any line 372 in that particular file, I assume it must be line 372 after transpilation. We have quite a couple of `StringLiterals` in that file, so I can't guess which one it is. Stryker says that it's not deleting the tmp folder, but unfortunately, that doesn't help us much, since:

```bash
~ $ ls -l .stryker-tmp/
total 0
```
I'm posting this already and I'll see if I can find anything else.

**Comment by kwisatz** [comment]
OK, I think I found the construct that it trips over:

```typescript
 watch: {
      'category.type'(categoryType) {
        if (this.isNew && this.category) {
          this.category.permissions = getDefaultDocumentCategoryPermissions(categoryType);
        }
      },
```

We have several of these in this file and commenting out one of them makes the placer fail on the next occurence:

```
18:28:18 (11676) ERROR Stryker Error: modules/web/src/document-categories/document-category-form.vue:376:6 expressionMutantPlacer could not place mutants with type(s): "StringLiteral". Either remove this file from the list of files to be mutated, or ignore the mutators. Please report this issue at https://github.com/stryker-mutator/stryker/issues/new?assignees=&labels=%F0%9F%90%9B+Bug&template=bug_report.md&title=expressionMutantPlacer%20could%20not%20place%20mutants%20with%20type(s)%3A%20%22StringLiteral%22.
```

What also prompted me to look at those was a log of the ast node that `placeMutants` tries to replace:

```
node:
   Node {
     type: 'StringLiteral',
     start: 7658,
     end: 7673,
     loc:
      SourceLocation {
        start: [Position],
        end: [Position],
        filename: undefined,
        identifierName: undefined },
     range: [ 2576, 2591 ],
     leadingComments: null,
     trailingComments: null,
     innerComments: null,
     extra: { rawValue: 'category.type', raw: '\'category.type\'' },
     value: 'category.type' 
    },
    type: 'StringLiteral',
```

**Comment by kwisatz** [comment]
I'm excluding `StringLiteral` mutators for now while we're checking if a StringLiteral containing a dot is even a valid thing. It works perfectly fine in production when bundled up by webpack though and the name is based on the property watched by vue. Maybe this is a hint that we should look into replacing the `watch` by something else though.

**Comment by kwisatz** [comment]
Replacing the function with an object while keeping the string literal as object key seems to work:

```typescript
watch: {
      'category.type': {
        handler(categoryType){
          if (this.isNew && this.category) {
            this.category.permissions = getDefaultDocumentCategoryPermissions(categoryType);
          }
        },
        deep: true,
      },
      […]
```

**Comment by nicojs** [comment]
Thanks a for your hard work on this!

I've added this code snippet to one of our integration tests:

```js
{
 watch: {
      'category.type'(categoryType) {
        if (this.isNew && this.category) {
          this.category.permissions = getDefaultDocumentCategoryPermissions(categoryType);
        }
      },
}
```

And sure enough, I've got the exact same error:

```
  1) instrumenter integration
       should be able to instrument a vue sample:
     TypeError: Cannot read property 'buildError' of undefined
```

We should be able to fix this (the error reporting as well as the root cause). 👍
