### ISSUE TITLE
Should Stryker run inform users of stryker init when stryker.conf.js cannot be found?

### ISSUE THREAD

**Issue by korthout** [stryker-mutator/stryker#332]
After installing Stryker locally, I tried to `run` Stryker. It informed me that the `stryker.conf.js` file is missing. We could inform users of the `stryker init` command for setting up this stryker.conf.js file. 

Do you think this is a good idea?

```
$ stryker run
[2017-06-21 09:08:22.870] [INFO] ConfigReader - Using stryker.conf.js in the current working directory.
[2017-06-21 09:08:22.873] [FATAL] ConfigReader - File ~/Development/infosupport/opensource/stryker/stryker-cli-test/stryker.conf.js does not exist!
[2017-06-21 09:08:22.874] [FATAL] ConfigReader - { Error: Cannot find module '~/Development/infosupport/opensource/stryker/stryker-cli-test/stryker.conf.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at ConfigReader.loadConfigModule (~/Development/infosupport/opensource/stryker/stryker-cli-test/node_modules/stryker/src/ConfigReader.js:38:32)
    at ConfigReader.loadConfigModule (~/Development/infosupport/opensource/stryker/stryker-cli-test/node_modules/stryker/src/ConfigReader.js:58:25)
    at ConfigReader.readConfig (~/Development/infosupport/opensource/stryker/stryker-cli-test/node_modules/stryker/src/ConfigReader.js:18:33)
    at new Stryker (~/Development/infosupport/opensource/stryker/stryker-cli-test/node_modules/stryker/src/Stryker.js:42:36)
    at Object.run (~/Development/infosupport/opensource/stryker/stryker-cli-test/node_modules/stryker/src/stryker-cli.js:56:31)
    at Object.<anonymous> (~/Development/infosupport/opensource/stryker/stryker-cli-test/node_modules/stryker/src/stryker-cli.js:59:22) code: 'MODULE_NOT_FOUND' }
```

**Comment by korthout** [comment]
@nicojs @simondel If you have a minute, what do you think about this?

**Comment by nicojs** [comment]
Great idea, you want to implement this?
