### ISSUE TITLE
Async/Await javascript support

### ISSUE THREAD

**Issue by webdevian** [stryker-mutator/stryker#521]
I get a parse error thrown in stryker / esprima for async methods on a class. It appears upgrading esprima to v4 will fix this - https://github.com/jquery/esprima/issues/1875#issuecomment-341885659

I've got no idea if this will have other side effects though

**Comment by simondel** [comment]
Odd. That means you are still using the ES5 mutator. Is this the same program that you opened #477 for? If that's not the case, could you try upgrading to the `stryker-javascript-mutator` as you did with the program in #477?

We won't be upgrading Esprima because the ES5 mutator is deprecated and will be removed soon.

**Comment by webdevian** [comment]
No it's a fresh install and init with `"stryker-javascript-mutator": "^0.2.3",`

**Comment by webdevian** [comment]
My config looks like this - 
```js
module.exports = config => {
  config.set({
    files: [
      {
        pattern: 'lib/**/*.js',
        included: true
      },
      {
        pattern: 'src/**/*.js',
        mutated: true,
        included: true
      },
      'test/**/*.js'
    ],
    testRunner: 'mocha',
    mutator: 'javascript',
    transpilers: [],
    reporter: ['html', 'baseline', 'clear-text', 'progress'],
    testFramework: 'mocha',
    coverageAnalysis: 'perTest'
  })
}
```

The error thrown is this:

```
[2017-12-04 12:55:42.624] [ERROR] StrykerCli - an error occurred Error: Could not transpile input files: Execute CoverageInstrumenterTranspiler: Error: Could not instrument "/Users/iegner/Code/huestatus/src/Hue.js" for code coverage. Error: Line 30: Unexpected identifier
Error: Line 30: Unexpected identifier
    at constructError (/Users/iegner/Code/huestatus/node_modules/istanbul/node_modules/esprima/esprima.js:2407:21)
    at createError (/Users/iegner/Code/huestatus/node_modules/istanbul/node_modules/esprima/esprima.js:2426:17)
    at unexpectedTokenError (/Users/iegner/Code/huestatus/node_modules/istanbul/node_modules/esprima/esprima.js:2500:13)
    at throwUnexpectedToken (/Users/iegner/Code/huestatus/node_modules/istanbul/node_modules/esprima/esprima.js:2505:15)
    at parseClassBody (/Users/iegner/Code/huestatus/node_modules/istanbul/node_modules/esprima/esprima.js:5147:21)
    at parseClassDeclaration (/Users/iegner/Code/huestatus/node_modules/istanbul/node_modules/esprima/esprima.js:5169:21)
    at parseStatementListItem (/Users/iegner/Code/huestatus/node_modules/istanbul/node_modules/esprima/esprima.js:3981:24)
    at parseFunctionSourceElements (/Users/iegner/Code/huestatus/node_modules/istanbul/node_modules/esprima/esprima.js:4869:23)
    at parseFunctionExpression (/Users/iegner/Code/huestatus/node_modules/istanbul/node_modules/esprima/esprima.js:5074:16)
    at parsePrimaryExpression (/Users/iegner/Code/huestatus/node_modules/istanbul/node_modules/esprima/esprima.js:3273:24)
Error: Could not instrument "/Users/iegner/Code/huestatus/src/Hue.js" for code coverage. Error: Line 30: Unexpected identifier
Error: Line 30: Unexpected identifier
    at constructError (/Users/iegner/Code/huestatus/node_modules/istanbul/node_modules/esprima/esprima.js:2407:21)
    at createError (/Users/iegner/Code/huestatus/node_modules/istanbul/node_modules/esprima/esprima.js:2426:17)
    at unexpectedTokenError (/Users/iegner/Code/huestatus/node_modules/istanbul/node_modules/esprima/esprima.js:2500:13)
    at throwUnexpectedToken (/Users/iegner/Code/huestatus/node_modules/istanbul/node_modules/esprima/esprima.js:2505:15)
    at parseClassBody (/Users/iegner/Code/huestatus/node_modules/istanbul/node_modules/esprima/esprima.js:5147:21)
    at parseClassDeclaration (/Users/iegner/Code/huestatus/node_modules/istanbul/node_modules/esprima/esprima.js:5169:21)
    at parseStatementListItem (/Users/iegner/Code/huestatus/node_modules/istanbul/node_modules/esprima/esprima.js:3981:24)
    at parseFunctionSourceElements (/Users/iegner/Code/huestatus/node_modules/istanbul/node_modules/esprima/esprima.js:4869:23)
    at parseFunctionExpression (/Users/iegner/Code/huestatus/node_modules/istanbul/node_modules/esprima/esprima.js:5074:16)
    at parsePrimaryExpression (/Users/iegner/Code/huestatus/node_modules/istanbul/node_modules/esprima/esprima.js:3273:24)
    at CoverageInstrumenterTranspiler.instrumentFile (/Users/iegner/Code/huestatus/node_modules/stryker/src/transpiler/CoverageInstrumenterTranspiler.js:87:19)
    at CoverageInstrumenterTranspiler.instrumentFileIfNeeded (/Users/iegner/Code/huestatus/node_modules/stryker/src/transpiler/CoverageInstrumenterTranspiler.js:67:25)
    at /Users/iegner/Code/huestatus/node_modules/stryker/src/transpiler/CoverageInstrumenterTranspiler.js:21:71
    at Array.map (<anonymous>)
    at CoverageInstrumenterTranspiler.transpile (/Users/iegner/Code/huestatus/node_modules/stryker/src/transpiler/CoverageInstrumenterTranspiler.js:21:36)
    at TranspilerFacade.<anonymous> (/Users/iegner/Code/huestatus/node_modules/stryker/src/transpiler/TranspilerFacade.js:45:62)
    at step (/Users/iegner/Code/huestatus/node_modules/tslib/tslib.js:129:27)
    at Object.next (/Users/iegner/Code/huestatus/node_modules/tslib/tslib.js:110:57)
    at /Users/iegner/Code/huestatus/node_modules/tslib/tslib.js:103:75
    at new Promise (<anonymous>)
    at InitialTestExecutor.<anonymous> (/Users/iegner/Code/huestatus/node_modules/stryker/src/process/InitialTestExecutor.js:54:31)
    at step (/Users/iegner/Code/huestatus/node_modules/tslib/tslib.js:129:27)
    at Object.next (/Users/iegner/Code/huestatus/node_modules/tslib/tslib.js:110:57)
    at fulfilled (/Users/iegner/Code/huestatus/node_modules/tslib/tslib.js:100:62)
    at <anonymous>
```

And the line in questions is this:

```js
/**
 * Represents a Hue Bridge
 * @extends BaseClass
 */
class Hue extends BaseClass {
  /**
   * @param  {Object} config Configuration
   */
  constructor (config) {
    super(config)
    this.log(`Loaded Config from ${config.config}:\n`, config)

    this.connection = new Huejay.Client({
      host: config.hue.host,
      port: config.hue.port,
      username: config.hue.username,
      timeout: config.hue.timeout
    })
  }

  /**
   * Load the bridge, lights and modules
   */
---> async init () {
    this.bridge = await this._getBridge()
    this.lamps = await this._getLamps()
    this.modules = await this._loadModules()
  }
```

**Comment by simondel** [comment]
Interesting.. It looks like Istanbul is causing the issue with their dependency on Esprima. Could you set `coverageAnalysis: 'off'` and then test if that fixes it?

**Comment by webdevian** [comment]
Yes it works with coverage analysis turned off

**Comment by webdevian** [comment]
Interestingly nyc coverage works ok though `"nyc": "^11.3.0"`

**Comment by webdevian** [comment]
This is the repo in question - https://github.com/APCOvernight/huestatus

**Comment by simondel** [comment]
That's probably because they have a direct dependency on the packages listed here: https://github.com/istanbuljs/istanbuljs which is the new monorepo for istanbul. 

We still use the core package of istanbul which has been deprecated: https://github.com/gotwarlost/istanbul 

I have created #524 to upgrade Istanbul. It may take a while so for now I would suggest disabling code coverage. Is that ok for you?

I'll also close the PR you created.

**Comment by webdevian** [comment]
Yeah that should be ok. I'll keep an eye on your new issue

**Comment by nowindowsowrking** [comment]
@simondel @webdevian I come across this, and just to mention it - Esprima have a lot of issues with the Async implementation. Acorn is closer to the specs, but I believe the Cherow parser - (*also uses nyc and istanbul*) - is the most correct one.
