### ISSUE TITLE
Can Stryker use for projects with Flow type? (https://flow.org/)

### ISSUE THREAD

**Issue by vmatheu** [stryker-mutator/stryker#545]
Can Stryker use for projects with Flow type?

**Comment by simondel** [comment]
Do you use `babel-preset-flow`? If that is the case, the [stryker-babel-transpiler](https://www.npmjs.com/package/stryker-babel-transpiler) combined with the [stryker-javascript-mutator](https://www.npmjs.com/package/stryker-javascript-mutator) may be what you're looking for. You can set this up when using our [quickstart](https://stryker-mutator.github.io/quickstart.html)

**Comment by guigonc** [comment]
Hi @simondel I work in this project with @vmatheu and our configurations is defined as follows.

`stryker.conf.json`
```
module.exports = function(config) {
  config.set({
    files: [
      { pattern: "src/**/*.*", mutated: true, included: false },
      "test/unit/**/*.js",
    ],
    testRunner: "mocha",
    mochaOptions: {
      recursive: true,
      compilers: ['js:babel-register', 'js:babel-polyfill'],
      require: ['ignore-styles']
    },
    mutator: "javascript",
    transpilers: ["babel"],
    reporter: ["html", "clear-text", "progress"],
    testFramework: "mocha",
    coverageAnalysis: "off",
    babelrcFile: ".babelrc"
  });
};
```
`package.json`
```
...
devDependencies: {
    ...
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-flow": "^6.23.0",
    "babel-preset-react": "^6.16.0",
...
```
`.babelrc`
```
{
  "presets": ["es2015", "react", "flow"],
  "plugins": ["transform-object-rest-spread", "transform-class-properties"]
}
```
But we still receive an error after the initial test run, and we can only pass through this error by erasing the flow types definition.
Here is the error.

```
[2017-12-11 13:37:35.441] [INFO] InitialTestExecutor - Initial test run succeeded. Ran 447 tests in 10 seconds.
[2017-12-11 13:37:35.453] [ERROR] StrykerCli - an error occurred { SyntaxError: Unexpected token (5:12)
    at Parser.pp$5.raise (/Users/ggoncalv/Projects/Latam/booking-webapp/node_modules/stryker-javascript-mutator/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/ggoncalv/Projects/Latam/booking-webapp/node_modules/stryker-javascript-mutator/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp.expectContextual (/Users/ggoncalv/Projects/Latam/booking-webapp/node_modules/stryker-javascript-mutator/node_modules/babylon/lib/index.js:1723:39)
    at Parser.pp$1.parseImport (/Users/ggoncalv/Projects/Latam/booking-webapp/node_modules/stryker-javascript-mutator/node_modules/babylon/lib/index.js:2869:10)
    at Parser.pp$1.parseStatement (/Users/ggoncalv/Projects/Latam/booking-webapp/node_modules/stryker-javascript-mutator/node_modules/babylon/lib/index.js:1884:49)
    at Parser.pp$1.parseBlockBody (/Users/ggoncalv/Projects/Latam/booking-webapp/node_modules/stryker-javascript-mutator/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/Users/ggoncalv/Projects/Latam/booking-webapp/node_modules/stryker-javascript-mutator/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/Users/ggoncalv/Projects/Latam/booking-webapp/node_modules/stryker-javascript-mutator/node_modules/babylon/lib/index.js:1673:17)
    at Object.parse (/Users/ggoncalv/Projects/Latam/booking-webapp/node_modules/stryker-javascript-mutator/node_modules/babylon/lib/index.js:7305:37)
    at Function.BabelParser.getAst (/Users/ggoncalv/Projects/Latam/booking-webapp/node_modules/stryker-javascript-mutator/src/helpers/BabelParser.js:15:27)
    at /Users/ggoncalv/Projects/Latam/booking-webapp/node_modules/stryker-javascript-mutator/src/JavaScriptMutator.js:21:45
    at Array.forEach (<anonymous>)
    at JavaScriptMutator.mutate (/Users/ggoncalv/Projects/Latam/booking-webapp/node_modules/stryker-javascript-mutator/src/JavaScriptMutator.js:20:98)
    at MutatorFacade.mutate (/Users/ggoncalv/Projects/Latam/booking-webapp/node_modules/stryker/src/MutatorFacade.js:13:14)
    at Stryker.mutate (/Users/ggoncalv/Projects/Latam/booking-webapp/node_modules/stryker/src/Stryker.js:81:31)
    at Stryker.<anonymous> (/Users/ggoncalv/Projects/Latam/booking-webapp/node_modules/stryker/src/Stryker.js:55:51) pos: 96, loc: Position { line: 5, column: 12 } }
```

Even if we remove the type definition we face the same problem on files with react components.

**Comment by simondel** [comment]
Very strange! Could you post the most simple bit of React code that is causing a crash? That way we can write a test for it and fix it 👍

**Comment by guigonc** [comment]
I've created a repo with the same configuration and the same error.

https://github.com/guigonc/stryker-test-config

**Comment by simondel** [comment]
Awesome! We can throw the content of one of those files directly in a unit test to see what happens and how we can fix it :) 

//cc @archcry

**Comment by Archcry** [comment]
Thank you for the test code, might be a problem with the JavaScript mutator not being able to parse flow.
See: https://github.com/babel/babel/tree/master/packages/babylon#plugins

Let's hope this issue can be resolved by adding the `flow` plug-in to Babylon.

**Comment by Archcry** [comment]
@guigonc, there are two problems.
One is the `stryker.conf.js`, you specified that you want to `mutated **/*.*` which will also try to mutate your html code. That's where the unexpected token pops up.
The other problem is babylon not being able to parse jsx without plugins, I will fix this today in conjunction with an extra extension check so it will not try to get the abstract syntax tree from html files.

**Comment by Archcry** [comment]
Pull-request that works with the provided test project is up.

**Comment by simondel** [comment]
@vmatheu @guigonc Could you guys upgrade your stryker-javascript-mutator to version 0.3.0 and test it again?

**Comment by guigonc** [comment]
@simondel I tested with @vmatheu in the example repository we posted on the thread and it worked. We are going to test on our real project and let you know!

**Comment by guigonc** [comment]
We checked that after the pull request `stryker` worked very well with `react` and `flow`, although it still fails with babel plugins. I pushed another commit in the example repository with a failing test for the `transform-object-rest-spread` plugin but it also failed with `transform-class-properties`. But the problem now is different from the one we have created the thread, so do you think it is better to close this issue and open another?

**Comment by Archcry** [comment]
A seperate issue would be nice. Would be better for future reference. I'll look into it anyways. Closing this for now.
