### ISSUE TITLE
Add VueJS support

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker#578]
We should be able to run mutation testing on VueJS projects.

Let's focus on the following setup right now: *Vue, Babel, Webpack, Jest*
And using Jest to execute the tests from a jest config file.

That would require the following Stryker plugins to be compatible:
* stryker-javascript-mutator
* stryker-jest-runner

## Do you have a VueJS app? Please let us know!
It would be awesome if it's open source but that's not a requirement.

Known users/setups:
@sir-code-a-lot: Vue, Babel, Webpack, Jest ([win-and-doni](https://github.com/gridonic/win-and-donic))
@ckjeldgaard: Vue, TypeScript, Jest ([vuejs-stryker-mutation](https://github.com/ckjeldgaard/vuejs-stryker-mutation)
@ckjeldgaard: Vue, TypeScript, Jest ([koncert](github.com/ckjeldgaard/koncert))

*The post above will be kept up-to-date and is subject to change!*

**Comment by simondel** [comment]
This will require at least https://github.com/stryker-mutator/stryker-jest-runner/pull/25

**Comment by ckjeldgaard** [comment]
The [example project with Vue, TypeScript and Jest](https://github.com/ckjeldgaard/vuejs-stryker-mutation) I created for [issue #453](https://github.com/stryker-mutator/stryker/issues/453) was a stripped down version of a similar and more "real" app using the same techologies. The project can be found at [github.com/ckjeldgaard/koncert](https://github.com/ckjeldgaard/koncert).

**Comment by simondel** [comment]
@ckjeldgaard Thanks! I updated the main post.

**Comment by lunafi-dorian** [comment]
I have a private vue project that can be tested when it is available.

**Comment by simondel** [comment]
Initial VueJS support is ready to be tested :) Checkout https://github.com/stryker-mutator/stryker-handbook/pull/4 and https://www.npmjs.com/package/stryker-vue-mutator

Let me know what you think!

**Comment by lunafi-dorian** [comment]
I get the same error everytime I run it (I have limited scope to mutate 2-3 files and tried on all):
```
18:18:59 (29936) ERROR InitialTestExecutor One or more tests failed in the initial test run:
	Layout shows large layout when media matches
```
Let me know if you have any thoughts, because all the unit tests pass atm.

Below is debugging output.

```
> stryker run

18:18:14 (29936) INFO ConfigReader Using stryker.conf.js in the current working directory.
18:18:14 (29936) DEBUG PluginLoader Loading stryker-* from /home/foo/Devel/foo/node_modules
18:18:14 (29936) DEBUG PluginLoader Loading plugins stryker-html-reporter (matched with expression stryker-*)
18:18:14 (29936) DEBUG PluginLoader Loading plugins stryker-javascript-mutator (matched with expression stryker-*)
18:18:14 (29936) DEBUG PluginLoader Loading plugins stryker-jest-runner (matched with expression stryker-*)
18:18:14 (29936) DEBUG PluginLoader Loading plugins stryker-vue-mutator (matched with expression stryker-*)
18:18:14 (29936) DEBUG PluginLoader Loading plugins stryker-html-reporter
18:18:14 (29936) DEBUG PluginLoader Loading plugins stryker-javascript-mutator
18:18:14 (29936) DEBUG PluginLoader Loading plugins stryker-jest-runner
18:18:14 (29936) DEBUG PluginLoader Loading plugins stryker-vue-mutator
18:18:15 (29948) DEBUG ChildProcessProxyWorker Changing current working directory for this process to /home/foo/Devel/foo/webapp/.stryker-tmp/sandbox6758407
18:18:15 (29948) DEBUG JestTestRunner Project root is /home/foo/Devel/foo/webapp/.stryker-tmp/sandbox6758407
18:18:15 (29936) DEBUG TimeoutDecorator Starting timeout timer (300000 ms) for a test run
18:18:59 (29936) DEBUG ChildProcessProxy Disposing of worker process 29948
18:18:59 (29936) DEBUG ChildProcessProxy Kill 29948
18:18:59 (29936) ERROR InitialTestExecutor One or more tests failed in the initial test run:
	Layout shows large layout when media matches
18:18:59 (29936) ERROR StrykerCli an error occurred Error: There were failed tests in the initial test run.
    at InitialTestExecutor.validateResult (/home/foo/Devel/foo/webapp/node_modules/stryker/src/process/InitialTestExecutor.js:112:27)
    at InitialTestExecutor.<anonymous> (/home/foo/Devel/foo/webapp/node_modules/stryker/src/process/InitialTestExecutor.js:45:30)
    at step (/home/foo/Devel/foo/webapp/node_modules/tslib/tslib.js:133:27)
    at Object.next (/home/foo/Devel/foo/webapp/node_modules/tslib/tslib.js:114:57)
    at fulfilled (/home/foo/Devel/foo/webapp/node_modules/tslib/tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
`stryker.conf.js`
```
module.exports = function(config) {
  config.set({
    logLevel: "debug",
    mutate: ["src/imports/startup/**/*.js", "src/imports/startup/**/*.vue"],
    mutator: "vue",
    testRunner: "jest",
    jest: {
      config: require("./tests/unit-test-setup/jest-config-ci.js")
    },
    reporters: ["progress", "clear-text", "html"],
    coverageAnalysis: "off"
  });
};
```
`jest-config-ci.js`
```
module.exports = {
  rootDir: './../../',
  roots: ['<rootDir>/src/'],
  coveragePathIgnorePatterns: [
    '<rootDir>/tests/',
    // collection definitions ignored from unit test coverage, no logic
    '<rootDir>/src/imports/modules/[a-zA-Z-]+/shared/collections/'
  ],
  testURL: 'http://www.meteor-vue-app.com',
  setupFiles: ['<rootDir>/tests/unit-test-setup/setup-tests.js'],
  verbose: false,
  collectCoverage: true,
  collectCoverageFrom: ['src/**/*', '!src/**/*-fixture.js'],
  coverageDirectory: '<rootDir>/tests/coverage/unit-tests/',
  moduleFileExtensions: ['js', 'vue'],
  transform: {
    '^.+\\.js$': 'babel-jest',
    '.*\\.(vue)$': 'jest-vue-preprocessor'
  },
  moduleNameMapper: {
    '^meteor/(.*)': '<rootDir>/tests/unit-test-setup/meteor-mocks/$1.js',
    '^[/](.*)': '<rootDir>/$1',
    'vue-meteor-tracker': '<rootDir>/node_modules/vue-meteor-tracker'
  },
  coverageThreshold: {
    global: {
      branches: 40,
      functions: 50,
      lines: 50,
      statements: 50
    }
  },
  coverageReporters: ['lcov'],
  reporters: ['default'],
  testResultsProcessor: './node_modules/jest-junit'
};
```
`package.json`
```
"vue": "^2.3.3"
"@babel/runtime": "7.0.0-beta.55"
"vue-template-compiler": "^2.3.3",
"jest": "^23.5.0",
"jest-junit": "^2.1.0",
"jest-vue-preprocessor": "^0.2.0",
```
`.babelrc`
```
{
  "env": {
    "test": {
      "presets": [
        "es2015",
        "es2017"
      ],
      "plugins": [
        "transform-object-rest-spread",
        "transform-runtime",
        "dynamic-import-node"
      ]
    }
  }
}
```

**Comment by simondel** [comment]
We've had the plugins for a while now. Since Stryker has changed a lot since then, I'm closing this issue for now. If people have issues running Vue projects, please open a new issue.
