### ISSUE TITLE
Karma test runner error in stryker-karma-runner

### ISSUE THREAD

**Issue by mjh5153** [stryker-mutator/stryker#582]
I have an Angular-cli project using typescript that I'm trying to use stryker on. I get the below error when I run stryker (stryker run). I'm using jasmine as the test framework and karma as the runner. Let me know if any other info is needed.
```
[2018-01-17 16:43:38.837] [ERROR] TestRunnerChildProcessAdapter - Error: No provider for "files"! (Resolving: framework:jasmine -> files)
    at error (/code/node_modules/di/lib/injector.js:22:12)
    at Object.get (/code/node_modules/di/lib/injector.js:9:13)
    at get (/code/node_modules/di/lib/injector.js:54:19)
    at /code/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at Array.invoke (/code/node_modules/di/lib/injector.js:70:31)
    at Injector.get (/code/node_modules/di/lib/injector.js:48:43)
    at /code/node_modules/karma/lib/server.js:143:20
    at Array.forEach (native)
    at Server._start (/code/node_modules/karma/lib/server.js:142:21)
    at Injector.invoke (/code/node_modules/di/lib/injector.js:75:15)
    at Server.start (/code/node_modules/karma/lib/server.js:103:18)
    at new KarmaTestRunner (/code/node_modules/stryker-karma-runner/src/KarmaTestRunner.js:48:22)
    at TestRunnerFactory.Factory.create (/code/node_modules/stryker-api/src/core/Factory.js:46:20)
    at IsolatedTestRunnerAdapterWorker.start (/code/node_modules/stryker/src/isolated-runner/IsolatedTestRunnerAdapterWorker.js:60:80)
    at process.<anonymous> (/code/node_modules/stryker/src/isolated-runner/IsolatedTestRunnerAdapterWorker.js:20:27)

[2018-01-17 16:43:38.845] [ERROR] TestRunnerChildProcessAdapter - Child process exited with non-zeroexit code 1. Last 10 message from the child process were:
        [2018-01-17 16:43:37.736] [DEBUG] PluginLoader - Loading plugins stryker-jasmine

        [2018-01-17 16:43:37.737] [DEBUG] PluginLoader - Loading plugins stryker-karma-runner

        [2018-01-17 16:43:38.547] [DEBUG] PluginLoader - Loading plugins stryker-mocha-framework

        [2018-01-17 16:43:38.549] [DEBUG] PluginLoader - Loading plugins stryker-mocha-runner

        [2018-01-17 16:43:38.555] [WARN] PluginLoader - Error during loading "stryker-mocha-runner" plugin:
  Cannot find module 'mocha'

        [2018-01-17 16:43:38.555] [DEBUG] PluginLoader - Loading plugins stryker-typescript

        [2018-01-17 16:43:38.583] [DEBUG] PluginLoader - Loading plugins stryker-webpack

        [2018-01-17 16:43:38.797] [DEBUG] PluginLoader - Loading plugins stryker-webpack-angular-preset

        [2018-01-17 16:43:38.798] [DEBUG] IsolatedTestRunnerAdapterWorker - Changing current workingdirectory for this process to /code/.stryker-tmp/sandbox2083576

        [2018-01-17 16:43:38.802] [INFO] KarmaTestRunner - using config
```

**Comment by Archcry** [comment]
Could you post your Stryker configuration so we can have a look at the options you have set?

**Comment by mjh5153** [comment]
module.exports = function(config) {
  config.set({
    files: ["src/**/*.ts"],
    testRunner: "karma",
    mutator: "typescript",
    transpilers: [],
    reporter: ["html", "baseline", "clear-text", "progress"],
    testFramework: "jasmine",
    coverageAnalysis: "off",
    karmaConfigFile: "karma.conf.js",
    tsconfigFile: "tsconfig.json",
    mutate: ["src/**/*.ts"]
  });
};

**Comment by Archcry** [comment]
I notices you did not configure a transpiler. I made some documentation on how to test Angular projects with Stryker right [here](https://github.com/Archcry/stryker-webpack-docs/blob/master/angular.md). You might want to take a look at that and see if it helps you out :D

**Comment by simondel** [comment]
@mjh5153 What kind of stryker packages do you have in your dependencies? It looks like you installed `stryker-mocha-runner` and `stryker-mocha-framework`:
```
[2018-01-17 16:43:38.547] [DEBUG] PluginLoader - Loading plugins stryker-mocha-framework

[2018-01-17 16:43:38.549] [DEBUG] PluginLoader - Loading plugins stryker-mocha-runner
```

You don't need to have those two plugins in your case and they cause your issue with mocha.

This together with the instructions by @Archcry should get you up and running!

**Comment by mjh5153** [comment]
That helped a lot. I'm getting the below error now on some scss files that my code includes. I unincluded those and now I'm only getting the below errors on the below file. Not sure why this one file is getting run by stryker because I'm only telling stryker to mutate one file.

[at-loader] Checking finished with 4 errors
[2018-01-18 19:44:36.699] [ERROR] StrykerCli - an error occurred Error: Could not transpile input files: Execute webpack: Error:
ERROR in [at-loader] ./src/app/quote/loan-request/detailed-loan-request/detailed-loan-request-form.component.spec.ts:257:7
    TS2554: Expected 0 arguments, but got 1.

ERROR in [at-loader] ./src/app/quote/loan-request/detailed-loan-request/detailed-loan-request-form.component.spec.ts:262:7
    TS2554: Expected 0 arguments, but got 1.

ERROR in [at-loader] ./src/app/quote/loan-request/detailed-loan-request/detailed-loan-request-form.component.spec.ts:268:7
    TS2554: Expected 0 arguments, but got 1.

ERROR in [at-loader] ./src/app/quote/loan-request/detailed-loan-request/detailed-loan-request-form.component.spec.ts:274:7
    TS2554: Expected 0 arguments, but got 1.
    at InitialTestExecutor.<anonymous> (/code/node_modules/stryker/src/process/InitialTestExecutor.js:54:31)
    at step (/code/node_modules/tslib/tslib.js:122:27)
    at Object.next (/code/node_modules/tslib/tslib.js:103:57)
    at fulfilled (/code/node_modules/tslib/tslib.js:93:62)

**Comment by simondel** [comment]
@mjh5153 Glad that you managed to get a bit further! Did you change the `files` and/or `mutate` properties in the stryker.conf.js by any chance? If that is the case, could you post the updated values?

**Comment by mjh5153** [comment]
module.exports = function(config) {
  config.set({
    files: [
    '!./**/*.ts',
    '!./**/*.js',
    '!./src/**/*.d.ts',
    '!./**/*.scss',
    {pattern : "src/app/app.component.ts", included: false, mutated: true},
     // Exclude test files to later include them again without the mutated flag set to true.
     '!./src/app/app.component.spec.ts',
     { pattern: './src/app/app.component.spec.ts', included: false, mutated: false },
     // Ignore environment configuration files.
     '!./src/environments/*.ts',
     // Other assets (HTML and CSS for the browser).
     './src/**/*.html',
     './src/**/*.css'

    ],
    testRunner: "karma",
    mutator: "typescript",
    transpilers: ["webpack"],
    reporter: ["html", "baseline", "clear-text", "progress"],
    testFramework: "jasmine",
    coverageAnalysis: "off", // Code coverage analysis is currently not supported in stryker-webpack.
    karmaConfigFile: "./stryker.karma.conf.js",
    tsconfigFile: "tsconfig.json",
    webpack: {
      project: 'angular' // Inform the stryker-webpack plugin that we want to use the angular preset.
   }
  });
};

**Comment by mjh5153** [comment]
```
module.exports = function(config) {
  config.set({
    files: [
    '!./**/*.ts',
    '!./**/*.js',
    '!./src/**/*.d.ts',
    '!./**/*.scss',
    {pattern : "src/app/app.component.ts", included: false, mutated: true},
     // Exclude test files to later include them again without the mutated flag set to true.
     '!./src/app/app.component.spec.ts',
     { pattern: './src/app/app.component.spec.ts', included: false, mutated: false },
     // Ignore environment configuration files.
     '!./src/environments/*.ts',
     // Other assets (HTML and CSS for the browser).
     './src/**/*.html',
     './src/**/*.css'

    ],
    testRunner: "karma",
    mutator: "typescript",
    transpilers: ["webpack"],
    reporter: ["html", "baseline", "clear-text", "progress"],
    testFramework: "jasmine",
    coverageAnalysis: "off", // Code coverage analysis is currently not supported in stryker-webpack.
    karmaConfigFile: "./stryker.karma.conf.js",
    tsconfigFile: "tsconfig.json",
    webpack: {
      project: 'angular' // Inform the stryker-webpack plugin that we want to use the angular preset.
   }
  });
};

**Comment by mjh5153** [comment]
Yes I did make a lot of changes

**Comment by mjh5153** [comment]
Any status on the above configuration for the angular-cli?

**Comment by nicojs** [comment]
Actually yes! We now kind of "officially" support angular-cli projects, though with a different setup. Could you try this one?

https://github.com/nicojs/angular-stryker-example

You'll have to uninstall `stryker-webpack` (deprecated) and install `stryker-webpack-transpiler`.

**Comment by simondel** [comment]
We're closing this issue for now. If you're having issues running the latest version of Stryker, let us know!
