### ISSUE TITLE
Strange error with new project

### ISSUE THREAD

**Issue by mscharley** [stryker-mutator/stryker#658]
### Summary

Ok, to start out with this is a bit of an edge case. I'm in the middle of starting up a new project with Stryker and ran into this though.

If you have less mutations than test runners you can run into cases where you will get the following error message printed:

```
generic-type-guard-cli: [2018-03-21 21:31:25.170] [ERROR] TestRunnerChildProcessAdapter - /Users/matthewscharley/Code/generic-type-guard/packages/generic-type-guard-cli/node_modules/graceful-fs/polyfills.js:21
generic-type-guard-cli:   chdir.call(process, d)
generic-type-guard-cli:         ^
generic-type-guard-cli: Error: ENOENT: no such file or directory, uv_chdir
generic-type-guard-cli:     at process.chdir (/Users/matthewscharley/Code/generic-type-guard/packages/generic-type-guard-cli/node_modules/graceful-fs/polyfills.js:21:9)
generic-type-guard-cli:     at IsolatedTestRunnerAdapterWorker.start (/Users/matthewscharley/Code/generic-type-guard/packages/generic-type-guard-cli/node_modules/stryker/src/isolated-runner/IsolatedTestRunnerAdapterWorker.js:59:17)
generic-type-guard-cli:     at process.<anonymous> (/Users/matthewscharley/Code/generic-type-guard/packages/generic-type-guard-cli/node_modules/stryker/src/isolated-runner/IsolatedTestRunnerAdapterWorker.js:20:27)
generic-type-guard-cli:     at emitTwo (events.js:126:13)
generic-type-guard-cli:     at process.emit (events.js:214:7)
generic-type-guard-cli:     at emit (internal/child_process.js:772:12)
generic-type-guard-cli:     at _combinedTickCallback (internal/process/next_tick.js:141:11)
generic-type-guard-cli:     at process._tickCallback (internal/process/next_tick.js:180:9)
generic-type-guard-cli: [2018-03-21 21:31:25.180] [ERROR] TestRunnerChildProcessAdapter - Child process exited with non-zero exit code 1. Last 10 message from the child process were:
generic-type-guard-cli:         [2018-03-21 21:31:24.938] [DEBUG] PluginLoader - Loading stryker-* from /Users/matthewscharley/Code/generic-type-guard/packages/generic-type-guard-cli/node_modules
generic-type-guard-cli:         [2018-03-21 21:31:24.941] [DEBUG] PluginLoader - Loading plugins stryker-html-reporter (matched with expression stryker-*)
generic-type-guard-cli:         [2018-03-21 21:31:24.941] [DEBUG] PluginLoader - Loading plugins stryker-mocha-framework (matched with expression stryker-*)
generic-type-guard-cli: [2018-03-21 21:31:24.941] [DEBUG] PluginLoader - Loading plugins stryker-mocha-runner (matched with expression stryker-*)
generic-type-guard-cli:         [2018-03-21 21:31:24.941] [DEBUG] PluginLoader - Loading plugins stryker-typescript (matched with expression stryker-*)
generic-type-guard-cli:         [2018-03-21 21:31:24.941] [DEBUG] PluginLoader - Loading plugins stryker-html-reporter
generic-type-guard-cli:         [2018-03-21 21:31:24.949] [DEBUG] PluginLoader - Loading plugins stryker-mocha-framework
generic-type-guard-cli:         [2018-03-21 21:31:24.950] [DEBUG] PluginLoader - Loading plugins stryker-mocha-runner
generic-type-guard-cli:         [2018-03-21 21:31:24.987] [DEBUG] PluginLoader - Loading plugins stryker-typescript
generic-type-guard-cli:         [2018-03-21 21:31:25.170] [DEBUG] IsolatedTestRunnerAdapterWorker - Changing current working directory for this processto /Users/matthewscharley/Code/generic-type-guard/packages/generic-type-guard-cli/.stryker-tmp/sandbox1383703
```

This implies that the sandbox has been cleaned up while it's still being used.

I've only run into this issue when the number of test runners exceeds the number of mutations to test. I've also not seen as many messages as I'd expect so there may also be a race condition involved!

### Stryker config

I'm not sure this is relevant, but this is my configuration. 

```js
module.exports = function(config) {
  config.set({
    files: [
      '!src/**/*.ts',
      {
        pattern: "src/**/*.ts",
        mutated: true,
        included: false
      },
      '!src/**/*.spec.ts',
      {
        pattern: "src/**/*.spec.ts",
        mutated: false,
        included: true
      }
    ],
    testRunner: "mocha",
    testFramework: "mocha",
    mochaOptions: {
      opts: "../../mocha.opts",
    },
    mutator: "typescript",
    transpilers: ["typescript"],
    tsconfigFile: "./tsconfig.json",
    reporter: ["clear-text", "html", "progress"],
    thresholds: { high: 100, low: 99, break: 95 },
    coverageAnalysis: "off"
  });
};
```

### Stryker environment

```
├─┬ stryker@0.19.3
├─┬ stryker-api@0.13.0
├─┬ stryker-html-reporter@0.12.1
├─┬ stryker-mocha-framework@0.8.3
├─┬ stryker-mocha-runner@0.10.5
├─┬ stryker-typescript@0.9.1
```

### Your Environment
| software         | version(s)
| ---------------- | -------  
| node             | 8.9.3
| npm              | 5.7.1
| Operating System | Mac OS 10.13.3

**Comment by simondel** [comment]
We've unfortunately missed this issue :( I'm closing it for now. If It's still present in the v1 release of Stryker, let us know!
