### ISSUE TITLE
TypeScript files fail to be found by Jest

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [stryker-mutator/stryker#919]
### Summary

I have a project with three relevant directories:

* `config/`: unrelated or miscellaneous configuration and setup scripts, such as polyfills and machine setup
* `src/`: actual source files in the application
* `test/`: config files specifically for tests, particularly unit tests

`stryker run` is failing to run Jest because no tests are found. When I look in the `.stryker-tmp/sandbox~~~~~~~` directory, `src/` exists, but only `.d.ts` files have been copied.

☹️.

```
[2018-06-28 12:01:18.456] [ERROR] TestRunnerChildProcessAdapter - Child process exited with non-zero exit code 1. Last 10 message from the child process were:
        [2018-06-28 12:01:14.832] [DEBUG] PluginLoader - Loading plugins stryker-webpack-transpiler (matched with expression stryker-*)

        [2018-06-28 12:01:14.832] [DEBUG] PluginLoader - Loading plugins stryker-baseline-reporter

        [2018-06-28 12:01:14.906] [DEBUG] PluginLoader - Loading plugins stryker-html-reporter

        [2018-06-28 12:01:14.939] [DEBUG] PluginLoader - Loading plugins stryker-jest-runner

        [2018-06-28 12:01:14.969] [DEBUG] PluginLoader - Loading plugins stryker-typescript

        [2018-06-28 12:01:15.503] [DEBUG] PluginLoader - Loading plugins stryker-webpack-transpiler

        [2018-06-28 12:01:17.209] [DEBUG] IsolatedTestRunnerAdapterWorker - Changing current working directory for this process to C:\Code\Client\.stryker-tmp\sandbox9151313

        [2018-06-28 12:01:17.210] [DEBUG] JestTestRunner - Project root is C:\Code\Client\.stryker-tmp\sandbox9151313

        [2018-06-28 12:01:17.247] [TRACE] JestPromiseTestAdapter - Invoking Jest with config {"collectCoverageFrom":["src/*/**/*.ts*","!src/*/**/*.stubs.ts*","!src/*","!src/*/Adapters/**","!src/*/External/**","!src/Browser/*","!src/BrowserMain/*","!src/Boot/*","!src/ServerSideRendering/*","!src/typings/**"],"coverageDirectory":"./reports/coverage","globals":{"ts-jest":{"tsConfigFile":"./tsconfig.test.json"}},"moduleFileExtensions":["js","ts","tsx"],"rootDir":"C:\\Code\\Client\\.stryker-tmp\\sandbox9151313","setupFiles":["<rootDir>/config/polyfills/nodePolyfills.js"],"setupTestFrameworkScriptFile":"<rootDir>/test/unit/setup","testMatch":["<rootDir>/src/**/?(*.)test.ts?(x)"],"transform":{"^.+\\.tsx?$":"ts-jest"},"collectCoverage":false,"verbose":false,"bail":false,"reporters":[]}

        No tests found
In C:\Code\Client\.stryker-tmp\sandbox9151313
  523 files checked.
  testMatch: C:\Code\Client\.stryker-tmp\sandbox9151313\src\**\?(*.)test.ts?(x) - 0 matches
  testPathIgnorePatterns: \\node_modules\\ - 523 matches
Pattern:  - 0 matches

[2018-06-28 12:01:18.464] [ERROR] StrykerCli - an error occurred Test runner child process exited with non-zero exit code 1
```

### Stryker config

```js
module.exports = function(config) {
    config.set({
        coverageAnalysis: "all",
        files: [
            "config/**/*.js",
            "config/**/*.js.map",
            "config/**/*.ts",
            "src/**/*.ts",
            "src/**/*.tsx",
            "test/unit/setup.js",
        ],
        mutate: [
            "src/**/*.ts",
            "src/**/*.tsx",
            "!src/**/*.d.ts",
        ],
        mutator: "typescript",
        reporter: ["baseline", "clear-text", "dashboard", "html", "progress"],
        testRunner: "jest",
        transpilers: ["typescript"],
        tsconfigFile: "tsconfig.json",
    });
};

```

### Stryker environment

```
    "stryker": "0.24.1",
    "stryker-api": "0.17.2",
    "stryker-baseline-reporter": "1.0.3",
    "stryker-cli": "0.1.3",
    "stryker-html-reporter": "0.14.2",
    "stryker-jest-runner": "0.7.0",
    "stryker-typescript": "0.11.2",
    "stryker-webpack-transpiler": "0.5.1",
```

### Your Environment
| software         | version(s)
| ---------------- | -------  
| node             | 10.X
| yarn              | 1.6.0
| Operating System | Windows 10

**Comment by nicojs** [comment]
Hi Joshua, thanks for reporting this issue.

The typescript files are not directly copied. Instead, they are first passed through the transpilers. You defined the typescript transpiler, so I would expect js and DTS files to be copied after transpiling.

In see you are using jest. Jest itself normally takes care of transpiling on the fly, no need for stryker to transpile typescript. Could you remove the typescript transpiler from your config and try again?

**Comment by JoshuaKGoldberg** [comment]
If I remove `transpilers`, I get this error:

```
[2018-06-28 13:13:51.213] [ERROR] StrykerCli - an error occurred Error: Could not instrument "D:\Code\WebClient\src\Authoring\Adapters\DraftJs\DraftJsUtils.test.ts" for code coverage. Inner error: SyntaxError: 'import' and 'export' may appear only with 'sourceType: "module"' (5:0)
SyntaxError: 'import' and 'export' may appear only with 'sourceType: "module"' (5:0)
    at Parser.pp$5.raise (D:\Code\WebClient\node_modules\babylon\lib\index.js:4454:13)
    at Parser.pp$1.parseStatement (D:\Code\WebClient\node_modules\babylon\lib\index.js:1881:16)
    at Parser.parseStatement (D:\Code\WebClient\node_modules\babylon\lib\index.js:5910:22)
    at Parser.pp$1.parseBlockBody (D:\Code\WebClient\node_modules\babylon\lib\index.js:2268:21)
    at Parser.pp$1.parseTopLevel (D:\Code\WebClient\node_modules\babylon\lib\index.js:1778:8)
    at Parser.parse (D:\Code\WebClient\node_modules\babylon\lib\index.js:1673:17)
    at Object.parse (D:\Code\WebClient\node_modules\babylon\lib\index.js:7305:37)
    at Instrumenter.instrumentSync (D:\Code\WebClient\node_modules\istanbul-lib-instrument\dist\instrumenter.js:123:31)
    at CoverageInstrumenterTranspiler.instrumentFile (D:\Code\WebClient\node_modules\stryker\src\transpiler\CoverageInstrumenterTranspiler.js:73:45)
    at CoverageInstrumenterTranspiler.instrumentFileIfNeeded (D:\Code\WebClient\node_modules\stryker\src\transpiler\CoverageInstrumenterTranspiler.js:65:25)
    at CoverageInstrumenterTranspiler.instrumentFile (D:\Code\WebClient\node_modules\stryker\src\transpiler\CoverageInstrumenterTranspiler.js:79:19)
    at CoverageInstrumenterTranspiler.instrumentFileIfNeeded (D:\Code\WebClient\node_modules\stryker\src\transpiler\CoverageInstrumenterTranspiler.js:65:25)
    at D:\Code\WebClient\node_modules\stryker\src\transpiler\CoverageInstrumenterTranspiler.js:19:80
    at Array.map (<anonymous>)
    at CoverageInstrumenterTranspiler.<anonymous> (D:\Code\WebClient\node_modules\stryker\src\transpiler\CoverageInstrumenterTranspiler.js:19:45)
    at step (D:\Code\WebClient\node_modules\stryker\node_modules\tslib\tslib.js:133:27)
    at Object.next (D:\Code\WebClient\node_modules\stryker\node_modules\tslib\tslib.js:114:57)
    at D:\Code\WebClient\node_modules\stryker\node_modules\tslib\tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (D:\Code\WebClient\node_modules\stryker\node_modules\tslib\tslib.js:103:16)
```

`sourceType: "module"` isn't a field option in styker.conf.js and does nothing.

**Comment by JoshuaKGoldberg** [comment]
I suppose `jest.config.js` might be useful?

```
/*!
 * Copyright Microsoft Corporation. All rights reserved.
 */

const path = require("path");

module.exports = {
	collectCoverageFrom: [
		"src/*/**/*.ts*",
		"!src/*/**/stubs.ts*",
		"!src/*/**/*.stubs.ts*",
		"!src/*",
		"!src/*/Adapters/**",
		"!src/*/External/**",
		"!src/Browser/*",
		"!src/BrowserMain/*",
		"!src/Boot/*",
		"!src/ServerSideRendering/*",
		"!src/typings/**",
	],
	coverageDirectory: "./reports/coverage",
	globals: {
		"ts-jest": {
			tsConfigFile: "./tsconfig.test.json",
		},
	},
	moduleFileExtensions: [
		"js",
		"ts",
		"tsx",
	],
	rootDir: path.join(__dirname, "../../"),
	setupFiles: [
		"<rootDir>/config/polyfills/nodePolyfills.js",
	],
	setupTestFrameworkScriptFile: "<rootDir>/test/unit/setup",
	testMatch: [
		"<rootDir>/src/**/?(*.)test.ts?(x)",
	],
	transform: {
		"^.+\\.tsx?$": "ts-jest",
	},
};
```

**Comment by nicojs** [comment]
Could you try and set `coverageAnalysis: 'off'`? I don't think it is supported yet for Jest.

**Comment by JoshuaKGoldberg** [comment]
Ah, that did it, thanks! I now get `v8::internal::FatalProcessOutOfMemory` errors on my 9486 mutations; will file a separate issue...

Is the lack of Jest support documented somewhere? Are there issues tracking adding it in?

**Comment by simondel** [comment]
> Is the lack of Jest support documented somewhere?

I don't think it's documented anywhere yet. Did you use `stryker init` to get your project up and running?

**Comment by JoshuaKGoldberg** [comment]
Yes, and it created approximately those settings.

**Comment by simondel** [comment]
@nicojs @mthmulders @Archcry Shall we change the jest runner to initialize Stryker with coverage analysis off?

**Comment by mthmulders** [comment]
Yes, we could forcibly turn it off. Or investigate the possibility of getting coverage analysis to work....

By the way, the lack of coverage analysis support [is documented](https://github.com/stryker-mutator/stryker-jest-runner/blob/master/README.md#configuring-stryker).

**Comment by nicojs** [comment]
Its clear we're still missing coherent documentation somewhere.

In the mean time, I've created a PR to turn coverage analysis of when `stryker init` is used and jest is configured: https://github.com/stryker-mutator/stryker-jest-runner/pull/55
